### ISSUE TITLE
Api v1.15.6 Response for Patching Deployment.Spec.Replicas: "unrecognized type: int32"

### ISSUE THREAD

**Issue by Vacant0mens** [kubernetes-client/python#1023]
**What happened (please include outputs or screenshots)**:
wrote some python to create a V1Deployment object and then patch or create the deployment based on whether it already exists or not. When the Deployment doesn't exist (using: `apps_v1.create_namespaced_deployment` , I get:
`"message":"Deployment in version \"v1\" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Replicas: readUint32: unexpected character: \ufffd, error found in #10 byte of ...`
If it _does_ exist (using: `apps_v1.patch_namespaced_deployment`), I get:
`"message":"unrecognized type: int32"`

I get no validation errors when creating the following objects:  `v1Pod`, `v1Container`, `v1PodDNSConfig`, `v1PodSpec`, `v1DeploymentSpec`, `v1Deployment`. It's only after calling patch or create when it hits the Api.

Code I'm using:
```
import kubernetes.client as kclient
import kubernetes.config as kconfig
from kubernetes.client.rest import ApiException
import yaml


class Kube:
    def __init__(self):
        kconfig.load_kube_config()
        self.apps_v1 = kclient.AppsV1Api()

    def create_deployment_object(self, match_labels, pod_spec, nameservers: list, pod_replicas, metadata):
        labels = kclient.V1ObjectMeta(labels=match_labels)
        v1pod = kclient.V1Pod(spec=pod_spec)
        v1container = kclient.V1Container(**v1pod.spec)
        dns_config = kclient.V1PodDNSConfig(nameservers=nameservers)
        v1podspec = kclient.V1PodSpec(containers=[v1container])
        v1deploymentspec = kclient.V1DeploymentSpec(
            selector=kclient.V1LabelSelector(
                match_labels=labels.labels
            ),
            template=kclient.V1PodTemplateSpec(
                spec=kclient.V1PodSpec(
                    **v1podspec.to_dict()),
                metadata=labels),
            replicas=pod_replicas
        )
        v1deployment = kclient.V1Deployment(metadata=kclient.V1ObjectMeta(
                **metadata),
            spec=v1deploymentspec)
        return v1deployment

    def deployment_exists(self, deployment_name, namespace_name):
        deployment_exists = False
        deployments = self.apps_v1.list_namespaced_deployment(namespace=namespace_name)
        print('Listing deployments with their replica counts:')
        print('Available\tSpec\tNamespace\tName')
        for i in deployments.items:
            print(f'{i.status.available_replicas}\t\t{i.spec.replicas}\t\t{i.metadata.namespace}\t{i.metadata.name}')
            if i.metadata.name == deployment_name:
                deployment_exists = True
        return deployment_exists

    def try_deployment(self, deployment: kclient.V1Deployment(), metadata: dict, namespace_namne):
        deployment_exists = self.deployment_exists(deployment_name=deployment.metadata.name,
                                                   namespace_name=namespace_name)
        if deployment_exists:
            print(f"Deployment {metadata.get('name')} found. Patching now.")
            updated = self.apps_v1.patch_namespaced_deployment(name=deployment.metadata.name,
                                                               namespace=namespace_name,
                                                               body=deployment, field_manager='Octopus')
            print(updated)
        else:
            print(f"Deployment {metadata.get('name')} not found. Creating now.")
            created = self.apps_v1.create_namespaced_deployment(namespace=namespace_name,
                                                                body=deployment, field_manager='Octopus')
            # dry_run='All')
            print(created)


if __name__ == '__main__':
    deployment_name = 'test'
    metadata = yaml.safe_load(f'name: {deployment_name}\nlabels:\n  app: {deployment_name}')
    namespace_name = '125-dev'
    kube = Kube()
    v1deployment = kube.create_deployment_object(match_labels=yaml.safe_load(f"'app': '{deployment_name}'"),
                                                 pod_spec=yaml.safe_load(f"""'name': "{deployment_name}"
image: nginx:latest
env:"""),
                                                 nameservers=['10.0.0.1', '10.0.0.2'],
                                                 pod_replicas="2",
                                                 metadata=yaml.safe_load(f'name: {deployment_name}\nlabels:\n  app: {deployment_name}'))
    print(v1deployment)
    kube.try_deployment(deployment=v1deployment, metadata=metadata, namespace_namne=namespace_name)
```

**What you expected to happen**:
Deployment should have been patched or created successfully

**How to reproduce it (as minimally and precisely as possible)**:
above code with  `deployment_name` and `namespace_name` (in the bottom/run section) assigned appropriately (namespace should already exist). Within the `v1deploymentspec` object assignment in `create_deployment_object()` If you comment-out `replicas=pod_replicas` and remove the comma above, create and patch work fine.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
(this is currently the default version for Rancher)
- OS (e.g., MacOS 10.13.6):
Ubuntu 18.04.3
- Python version (`python --version`)
3.7.4
- Python client version (`pip list | grep kubernetes`)
10.0.1

**Comment by Vacant0mens** [comment]
@roycaihw do you know if this can be fixed in the kubernetes-client/python v10 or if it's just an incompatibility issue?

**Comment by roycaihw** [comment]
I didn't find any incompatibility issue for 1.15.6-v10 version skew. Could you turn on the [debug](https://github.com/kubernetes-client/python/blob/ccd3ce4fc27ed202864f9b3f971744a5ebf6ad7e/kubernetes/client/configuration.py#L76) switch in your client Configuration and paste the complete API request & response?

**Comment by Vacant0mens** [comment]
@roycaihw I'm not familiar with the underlying code for the python module. Where do I turn on that switch? I'm just calling `kconfig.load_kube_config()` (first line in my `__init__()` ). Does that mean I'd put it in my `~/.kube/config` file?

**Comment by roycaihw** [comment]
you can do

```
    def __init__(self):
        kconfig.load_kube_config()
        configuration = kclient.Configuration()
        configuration.debug = True
        self.apps_v1 = kclient.AppsV1Api(api_client=client.ApiClient(configuration=configuration))
```

**Comment by Vacant0mens** [comment]
Here's the output with Debug set (minus my `print()`'s)
```
2019-12-13 09:09:50,715 DEBUG Starting new HTTPS connection (1): rancher.goldpointdev.com:443
send: b'GET /k8s/clusters/c-qrt2v/apis/apps/v1/namespaces/125-dev/deployments HTTP/1.1\r\nHost: rancher.goldpointdev.com\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/10.0.1/python\r\nauthorization: Bearer kubeconfig-user-cctpf.c-qrt2v:h5244qc4q9p4sb7nmfsfxxlqlnndt9kcnwbn8hv2xb2zx5bxmk2z6q\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json
header: Date: Fri, 13 Dec 2019 16:09:51 GMT
header: Transfer-Encoding: chunked
2019-12-13 09:09:50,741 DEBUG https://rancher.goldpointdev.com:443 "GET /k8s/clusters/c-qrt2v/apis/apps/v1/namespaces/125-dev/deployments HTTP/1.1" 200 None
send: b'PATCH /k8s/clusters/c-qrt2v/apis/apps/v1/namespaces/125-dev/deployments/productsetup?fieldManager=Octopus HTTP/1.1\r\nHost: rancher.goldpointdev.com\r\nAccept-Encoding: identity\r\nContent-Length: 697\r\nAccept: application/json\r\nContent-Type: application/strategic-merge-patch+json\r\nUser-Agent: Swagger-Codegen/10.0.1/python\r\nauthorization: Bearer kubeconfig-user-cctpf.c-qrt2v:h5244qc4q9p4sb7nmfsfxxlqlnndt9kcnwbn8hv2xb2zx5bxmk2z6q\r\n\r\n'
send: b'{"metadata": {"labels": {"app": "productsetup"}, "name": "productsetup"}, "spec": {"replicas": "2", "selector": {"matchLabels": {"app": "productsetup"}}, "template": {"metadata": {"labels": {"app": "productsetup"}}, "spec": {"containers": [{"args": null, "command": null, "env": null, "env_from": null, "image": "nginx:latest", "image_pull_policy": null, "lifecycle": null, "liveness_probe": null, "name": "productsetup", "ports": null, "readiness_probe": null, "resources": null, "security_context": null, "stdin": null, "stdin_once": null, "termination_message_path": null, "termination_message_policy": null, "tty": null, "volume_devices": null, "volume_mounts": null, "working_dir": null}]}}}}'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Content-Length: 117
header: Content-Type: application/json
header: Date: Fri, 13 Dec 2019 16:09:51 GMT
2019-12-13 09:09:50,777 DEBUG https://rancher.goldpointdev.com:443 "PATCH /k8s/clusters/c-qrt2v/apis/apps/v1/namespaces/125-dev/deployments/productsetup?fieldManager=Octopus HTTP/1.1" 500 117
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/VSWorkspaces/GitRepos/PyKubernetes/test.py", line 104, in <module>
    kube.try_deployment(deployment=v1deployment, metadata=metadata, namespace_namne=namespace_name)
  File "D:/VSWorkspaces/GitRepos/PyKubernetes/test.py", line 81, in try_deployment
    body=deployment, field_manager='Octopus')
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\apis\apps_v1_api.py", line 3623, in patch_namespaced_deployment
    (data) = self.patch_namespaced_deployment_with_http_info(name, namespace, body, **kwargs)
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\apis\apps_v1_api.py", line 3723, in patch_namespaced_deployment_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\api_client.py", line 393, in request
    body=body)
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\rest.py", line 286, in PATCH
    body=body)
  File "C:\Users\tommyc\Desktop\Scripts\venv\lib\site-packages\kubernetes\client\rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Length': '117', 'Content-Type': 'application/json', 'Date': 'Fri, 13 Dec 2019 16:09:51 GMT'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unrecognized type: int32","code":500}
```

**Comment by roycaihw** [comment]
Sorry for the late response. The apiserver rejected the request because it expects V1DeploymentSpec to be an int, but you were sending a string `"replicas": "2"`. Changing it to `"replicas": 2` resolves the issue

/close
