### ISSUE TITLE
List Pods Example Fails. Seems to be a package conflict with urllib3.

### ISSUE THREAD

**Issue by orlando-jamie** [kubernetes-client/python#1046]
**What happened (please include outputs or screenshots)**:
Trying to start a project using this Kubernetes client. However, when I install the package in a fresh virtual environment, the list pods example code in the read me fails.

```bash
kubeTest$ python3 -m venv venv

kubeTest$ source venv/bin/activate

(venv) kubeTest$ pip install kubernetes
Collecting kubernetes
  Using cached https://files.pythonhosted.org/packages/6e/fc/2cab119f679648b348b8940de0dd744a1f0ee99c690aa2ef6072f050816c/kubernetes-10.0.1-py2.py3-none-any.whl
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl
Collecting requests-oauthlib (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting pyyaml>=3.12 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/8d/c9/e5be955a117a1ac548cdd31e37e8fd7b02ce987f9655f5c7563c656d5dcb/PyYAML-5.2.tar.gz
Collecting six>=1.9.0 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting urllib3>=1.24.2 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting requests (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=21.0.0 in ./venv/lib/python3.7/site-packages (from kubernetes) (40.8.0)
Collecting python-dateutil>=2.5.3 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting certifi>=14.05.14 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting google-auth>=1.0.1 (from kubernetes)
  Using cached https://files.pythonhosted.org/packages/36/f8/84b5771faec3eba9fe0c91c8c5896364a8ba08852c0dea5ad2025026dd95/google_auth-1.10.0-py2.py3-none-any.whl
Collecting oauthlib>=3.0.0 (from requests-oauthlib->kubernetes)
  Using cached https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->kubernetes)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->kubernetes)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cachetools<5.0,>=2.0.0 (from google-auth>=1.0.1->kubernetes)
  Using cached https://files.pythonhosted.org/packages/08/6a/abf83cb951617793fd49c98cb9456860f5df66ff89883c8660aa0672d425/cachetools-4.0.0-py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.0.1->kubernetes)
  Using cached https://files.pythonhosted.org/packages/52/50/bb4cefca37da63a0c52218ba2cb1b1c36110d84dcbae8aa48cd67c5e95c2/pyasn1_modules-0.2.7-py2.py3-none-any.whl
Collecting rsa<4.1,>=3.1.4 (from google-auth>=1.0.1->kubernetes)
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes)
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Installing collected packages: six, websocket-client, oauthlib, idna, certifi, urllib3, chardet, requests, requests-oauthlib, pyyaml, python-dateutil, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, kubernetes
  Running setup.py install for pyyaml ... done
Successfully installed cachetools-4.0.0 certifi-2019.11.28 chardet-3.0.4 google-auth-1.10.0 idna-2.8 kubernetes-10.0.1 oauthlib-3.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.7 python-dateutil-2.8.1 pyyaml-5.2 requests-2.22.0 requests-oauthlib-1.3.0 rsa-4.0 six-1.13.0 urllib3-1.25.7 websocket-client-0.57.0
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv) kubeTest$ cd kubeTest/

(venv) kubeTest$ ./kubeTest.py
{"msg": "starting kubeTest", "hostname": "BLAH", "timestamp": "2019-12-31T13:27:01.828984", "log_level": "INFO", "script": "kubeTest.py"}
Traceback (most recent call last):
  File "./kubeTest.py", line 97, in <module>
    main()
  File "./kubeTest.py", line 60, in main
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13630, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13724, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 654, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
    return conn or self._new_conn()
  File "/blah/kubeTest/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 959, in _new_conn
    self.port or "443",
TypeError: debug() takes 2 positional arguments but 5 were given
```

**What you expected to happen**:
I would expect the example code to run.

**How to reproduce it (as minimally and precisely as possible)**:
1. Fresh python3 virtual environment on OSX 10.14.6.
2. pip install kubernetes
3. run list pods example script from the read me

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): N/A
- OS (e.g., MacOS 10.13.6): MacOS 10.14.6
- Python version (`python --version`): Python 3.7.4
- Python client version (`pip list | grep kubernetes`): kubernetes 10.0.1

**Comment by orlando-jamie** [comment]
Turns out this was self-induced. Closing as not a bug.
