### ISSUE TITLE
Running first sample code (get pods) lead to a crash on OpenShift 3.11 (kubernete 1.11) (TypeError: argument of type 'NoneType' is not iterable in kube_config.py)

### ISSUE THREAD

**Issue by bsergean** [kubernetes-client/python#1060]
**What happened (please include outputs or screenshots)**:

```
~ $ python kube_test.py
Traceback (most recent call last):
  File "kube_test.py", line 4, in <module>
    config.load_kube_config()
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 643, in load_kube_config
    loader = _get_kube_config_loader_for_yaml_file(
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 610, in _get_kube_config_loader_for_yaml_file
    return KubeConfigLoader(
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 495, in __getitem__
    v = self.safe_get(key)
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 491, in safe_get
    key in self.value):
TypeError: argument of type 'NoneType' is not iterable
```

**What you expected to happen**:

Same command terminates without throwing an exception.

**How to reproduce it (as minimally and precisely as possible)**:

Run the command, as a normal user (not sure what that means ... I'm not an admin on the kubernete/openshift cluster) from inside a container/pod.

```
~ $ cat kube_test.py 
from kubernetes import client, config

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))

~ $ python kube_test.py 
Traceback (most recent call last):
....
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`)
- Python client version (`pip list | grep kubernetes`)

```
OpenShift Master:
    v3.11.0+13fd842-146 
Kubernetes Master:
    v1.11.0+d4cacc0 
OpenShift Web Console:
    v3.11.0+ea42280
```

I'm using python 3.8.1, from an alpine container (python:3.8.1-alpine3.11)
and kubernetes==10.0.1

**Comment by bsergean** [comment]
I added `config.load_incluster_config()` by following the 'Accessing the API from within a Pod' section in this [doc](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/), and I'm now getting a different error, which look more reasonable.

```
~ $ 
~ $ python kube_test.py 
Listing pods with their IPs:
Traceback (most recent call last):
  File "kube_test.py", line 10, in <module>
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/apis/core_v1_api.py", line 13630, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/apis/core_v1_api.py", line 13711, in list_pod_for_all_namespaces_with_http_info
    return self.api_client.call_api('/api/v1/pods', 'GET',
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 330, in call_api
    return self.__call_api(resource_path, method,
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    response_data = self.request(method, url,
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 351, in request
    return self.rest_client.GET(url,
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 227, in GET
    return self.request("GET", url,
  File "/home/app/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '916f3240-5622-45e6-bd09-dd7b049fe057', 'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 24 Jan 2020 05:40:39 GMT', 'Content-Length': '270'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:cobra-live:default\" cannot list pods at the cluster scope: no RBAC policy matched","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```

**Comment by bsergean** [comment]
What I am trying to do is list all the IP for all the services running in this namespace:

```
redis11             ClusterIP   172.16.18.181    <none>        6379/TCP,16379/TCP   10d
redis12             ClusterIP   172.16.51.165    <none>        6379/TCP,16379/TCP   10d
redis13             ClusterIP   172.16.97.13     <none>        6379/TCP,16379/TCP   10d
redis14             ClusterIP   172.16.78.24     <none>        6379/TCP,16379/TCP   10d
redis15             ClusterIP   172.16.242.225   <none>        6379/TCP,16379/TCP   10d
redis16             ClusterIP   172.16.124.204   <none>        6379/TCP,16379/TCP   10d
redis17             ClusterIP   172.16.2.163     <none>        6379/TCP,16379/TCP   10d
redis18             ClusterIP   172.16.216.4     <none>        6379/TCP,16379/TCP   10d
```

Is there an API to do that ?

**Comment by roycaihw** [comment]
Could you also provide your kubeconfig file?

**Comment by roycaihw** [comment]
> What I am trying to do is list all the IP for all the services running in this namespace:

What kubectl command were you using? If you run `--v=8` with it, you will see what API endpoints kubectl was calling, and you will be able to use this python client to call those API endpoints.

**Comment by bsergean** [comment]
Indeed I think it's an RBAC permission issue. One exception carry this message: `"message":"pods is forbidden`.

`Reason: Forbidden` is also a good hint. Maybe the error message could be decorated with some hints on how to fix things, but that's a different discussion.

Thanks for the help !
