### ISSUE TITLE
`create_namespaced_horizontal_ pod_autoscaler` throws  ValueError: Invalid value for `conditions`, must not be `None`                                                                                                         

### ISSUE THREAD

**Issue by savitha-suresh** [kubernetes-client/python#1098]
```Traceback (most recent call last): 
File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/apis/autoscaling_v2beta1_api.py", line 60, in create_namespaced_horizontal_pod_autoscaler                                                                                                                                                
    (data) = self.create_namespaced_horizontal_pod_autoscaler_with_http_info(namespace, body, **kwargs)                                                       
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/apis/autoscaling_v2beta1_api.py", line 151, in create_namespaced_horizontal
_pod_autoscaler_with_http_info                                                                                                                                
    collection_formats=collection_formats)                                                                                                                    
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api                                      
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)                                                                           
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api                                    
    return_data = self.deserialize(response_data, response_type)                                                                                              
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 249, in deserialize                                   
    return self.__deserialize(data, response_type)                                                                                                            
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 289, in __deserialize                                 
    return self.__deserialize_model(data, klass)                                                                                                              
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 633, in __deserialize_model                           
    kwargs[attr] = self.__deserialize(value, attr_type)                                                                                                       
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 289, in __deserialize                                 
    return self.__deserialize_model(data, klass)                                                                                                              
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 635, in __deserialize_model                           
    instance = klass(**kwargs)                                                                                                                                
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/models/v2beta1_horizontal_pod_autoscaler_status.py", line 64, in __init__  
    self.conditions = conditions                                                                                                                              
  File "/virutalenv/lib/python3.6/site-packages/kubernetes/client/models/v2beta1_horizontal_pod_autoscaler_status.py", line 95, in conditions
    raise ValueError("Invalid value for `conditions`, must not be `None`")                                                                                    
ValueError: Invalid value for `conditions`, must not be `None`
```
code to reproduce - 
```
from kubernetes import client
k8s_api = client.AutoscalingV2beta1Api()
k8s_api.create_namespaced_horizontal_pod_autoscaler(namespace='default',
body=client.V2beta2HorizontalPodAutoscaler(
        api_version='autoscaling/v2beta2',
        kind='HorizontalPodAutoscaler',
        metadata=client.V1ObjectMeta(
            name=scaler_name
        ),
        spec=client.V2beta2HorizontalPodAutoscalerSpec(
            scale_target_ref=client.V2beta2CrossVersionObjectReference(
                api_version=version1,
                kind=scalable_object,
                name=app_name
            ),
            min_replicas=N1,
            max_replicas=N2,
            metrics=[client.V2beta2MetricSpec(
                type='Object',
                object=client.V2beta2ObjectMetricSource(
                    metric=client.V2beta2MetricIdentifier(
                        name=metric_name
                    ),
                    described_object=client.V2beta2CrossVersionObjectReference(
                        api_version=version2,
                        kind=scalable_object,
                        name=app_name
                    ),
                    target=client.V2beta2MetricTarget(
                        type=target_type,
                        value=target_value
                    )
                ),

            )]
        ),
    )
```
This returns the exception i posted above, though it create the hpa. status is optional in V2beta2HorizontalPodAutoscaler, why does this exception occur and what is the work around for this?

**Comment by GrahamDumpleton** [comment]
There is a similar issue with creating CRDs. For CRDs, the workaround is to use the ``wrapt`` module to monkey patch the code to temporarily fix it. For the CRD case one can use:

```
import wrapt

def fix_V1beta1CustomResourceDefinitionStatus___init__(wrapped, instance, args, kwargs):
    def _resolve(accepted_names=None, conditions=[], stored_versions=[]):
        return accepted_names, conditions, stored_versions

    accepted_names, conditions, stored_versions = _resolve(*args, **kwargs)

    return wrapped(
            accepted_names=accepted_names,
            conditions=conditions or [],
            stored_versions=stored_versions or [])

wrapt.wrap_function_wrapper(
        'kubernetes.client.models.v1beta1_custom_resource_definition_status',
        'V1beta1CustomResourceDefinitionStatus.__init__',
        fix_V1beta1CustomResourceDefinitionStatus___init__)
```

You could craft a similar monkey patch for ``V2beta2HorizontalPodAutoscaler``.

**Comment by tdmalone** [comment]
Related: https://github.com/kubernetes-client/python/issues/1022
Looks like it'll be fixed when v12 of this client is released.

**Comment by tdmalone** [comment]
Aand, here's another potential workaround method: https://github.com/kubernetes-client/python/issues/553#issuecomment-510577028
So that's at least 3 to choose from in this ticket :)

**Comment by abhishekdhotre** [comment]
Still facing the issue using kubernetes-12.0.1 and kubernetes v 1.17, any updates?
