### ISSUE TITLE
Unable to create Service with create_namespaced_service

### ISSUE THREAD

**Issue by rajivreddy** [kubernetes-client/python#1123]
**What happened (please include outputs or screenshots)**:
```python
from kubernetes import config, client, watch
import json
config.load_kube_config()
v1 = client.CoreV1Api()

manifest = {
'apiVersion': 'v1',
    'kind': 'Service',

    'metadata': {
        "name": "test"
    },
    'spec': {
        'selector': {
            "app" : "frontend"
        },
        'ports': [
            {
                'protocol': 'TCP',
                'port': 80,
                'targetPort': 80
            }
        ]
    }
}
# print(body)
# print(json.dumps(manifest))
api_response = v1.create_namespaced_service(namespace="default", body=json.dumps(manifest),pretty='true')
```

**What you expected to happen**:
Should able to create Service 
**How to reproduce it (as minimally and precisely as possible)**:
You can use the above code
**Anything else we need to know?**:
Error log:
```
Traceback (most recent call last):
  File "crete_svc.py", line 57, in <module>
    api_response = v1.create_namespaced_service_with_http_info(namespace="default", body=json.dumps(manifest),pretty='true')
  File "/Users/rajeev/PycharmProjects/examplecontroller/venv/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7093, in create_namespaced_service_with_http_info
    collection_formats=collection_formats)
  File "/Users/rajeev/PycharmProjects/examplecontroller/venv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/Users/rajeev/PycharmProjects/examplecontroller/venv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/rajeev/PycharmProjects/examplecontroller/venv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 388, in request
    body=body)
  File "/Users/rajeev/PycharmProjects/examplecontroller/venv/lib/python3.7/site-packages/kubernetes/client/rest.py", line 278, in POST
    body=body)
  File "/Users/rajeev/PycharmProjects/examplecontroller/venv/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 26 Mar 2020 13:13:17 GMT', 'Content-Length': '489'})
HTTP response body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Service): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" } (227b5c2261706956657273696f6e5c223a205c2276315c222c205c226b69 ...)",
  "reason": "BadRequest",
  "code": 400
}

```
**Environment**: Python 3.7
- Kubernetes version (`kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6): `MacOS 10.15.4`
- Python version : `Python 3.7`
- Python client version: `kubernetes        11.0.0  `

**Comment by yliaog** [comment]
please follow the example in 
https://github.com/kubernetes-client/python/blob/master/examples/deployment_create.py

it looks that manifest provided is *not* valid
