### ISSUE TITLE
Need API help: watching pod's new events only

### ISSUE THREAD

**Issue by poul1x** [kubernetes-client/python#1134]
Hello, I need to get all **new** events of my pods, but listing events using [this](https://github.com/kubernetes-client/python/blob/master/examples/pod_namespace_watch.py) example gives me old events too. How can I filter out all events that have already happened?

**Comment by poul1x** [comment]
Now I have to delete all old events of a namespace.

**Comment by poul1x** [comment]
Code
```python
from kubernetes import client, config, watch

config.load_kube_config()

v1 = client.CoreV1Api()
w = watch.Watch()
namespace='fuzzing'
for event in w.stream(v1.list_namespaced_pod, namespace=namespace):
    print("Event: %s %s" % (event['type'], event['object'].metadata.name))
    v1.delete_namespaced_event(event['object'].metadata.name, namespace)
```

Output
```
Event: ADDED fuzzer-5xmj7
Traceback (most recent call last):
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\app\kube_sync.py", line 15, in <module>
    v1.delete_namespaced_event(event['object'].metadata.name, namespace)
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\api\core_v1_api.py", line 9789, in delete_namespaced_event
    (data) = self.delete_namespaced_event_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\api\core_v1_api.py", line 9889, in delete_namespaced_event_with_http_info
    collection_formats=collection_formats)
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\api_client.py", line 345, in 
call_api
    _preload_content, _request_timeout)
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\api_client.py", line 176, in 
__call_api
    _request_timeout=_request_timeout)
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\api_client.py", line 411, in 
request
    body=body)
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\rest.py", line 268, in DELETE
    body=body)
  File "c:\Users\Pavel Knyazev\Documents\Projects\Fuzz-farm\starter\venv\lib\site-packages\kubernetes\client\rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 09 Apr 2020 18:09:25 GMT', 'Content-Length': '196'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"events \"fuzzer-5xmj7\" not found","reason":"NotFound","details":{"name":"fuzzer-5xmj7","kind":"events"},"code":404}
```

I don't understand, are you caching old events? I've run that pod one day ago
