### ISSUE TITLE
import error python 3.5

### ISSUE THREAD

**Issue by carpdm** [kubernetes-client/python#1135]
```
>>> from kubernetes import client, config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/__init__.py", line 20, in <module>
    import kubernetes.config
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/config/__init__.py", line 17, in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/config/kube_config.py", line 29, in <module>
    import google.auth.transport.requests
  File "/usr/local/lib/python3.5/dist-packages/google/auth/transport/requests.py", line 38, in <module>
    from requests.packages.urllib3.util.ssl_ import (
ImportError: cannot import name 'create_urllib3_context'
```

**Comment by carpdm** [comment]
Well, I have fixed this error, it was a version mismatch of `requests`.
I just reinstall requests like and get this error clear.
