### ISSUE TITLE
Missing the required parameter `namespaces`

### ISSUE THREAD

**Issue by tsusadivyago** [kubernetes-client/python#1154]
**What happened (please include outputs or screenshots)**:
Traceback (most recent call last):
  File "C:/Users/..../Documents/pycharm/k8s/myScripts/deployments/create_deployment.py", line 49, in <module>
    ret = v1.create_namespaced_deployment(namespace=namespace, body=deployment)
  File "C:\Users\....\Documents\pycharm\k8s\venv\lib\site-packages\kubernetes\client\apis\apps_v1_api.py", line 290, in create_namespaced_deployment
    (data) = self.create_namespaced_deployment_with_http_info(namespace, body, **kwargs)
  File "C:\Users\.....\Documents\pycharm\k8s\venv\lib\site-packages\kubernetes\client\apis\apps_v1_api.py", line 329, in create_namespaced_deployment_with_http_info
    raise ValueError("Missing the required parameter `namespaces` when calling `create_namespaced_deployment`")
ValueError: Missing the required parameter `namespaces` when calling `create_namespaced_deployment`

**What you expected to happen**:
deployment should be created

**How to reproduce it (as minimally and precisely as possible)**:
create a deployment using client.AppsV1Api()

**Anything else we need to know?**:
all the apis need 'namespaces' parameter.
issue is observed here is in: \Lib\site-packages\kubernetes\client\apis\apps_v1_api.py

- all_params = ['name', 'namespaces', 'pretty'

-         if ('namespaces' not in params) or (params['namespaces'] is None):
            raise ValueError("Missing the required parameter `namespaces` when calling `delete_namespaced_daemon_set`")

-         if 'namespaces' in params:
            path_params['namespaces'] = params['namespaces']

- call_api('/apis/apps/v1/namespaces/{namespaces}/daemonsets/{name}',

-and in swagger_types and attribute_map of \Lib\site-packages\kubernetes\client\models\v1_object_meta.py

what i noted in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#create-21
the api for create deployment is "POST /apis/apps/v1/namespaces/{namespace}/deployments".

Its namespace and not namespaces

**Environment**:
- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6):
CentOS Linux 7

- Python version (`python --version`)
Python 3.6.8

- Python client version (`pip list | grep kubernetes`)
kubernetes        10.0.1

**Comment by tsusadivyago** [comment]
upgraded to kubernetes 11.0.0
