### ISSUE TITLE
Error creating ServicePort, Invalid value for `port`, must not be `None`

### ISSUE THREAD

**Issue by jicowan** [kubernetes-client/python#1199]
**What happened (please include outputs or screenshots)**:
When the following code runs
```
    if 'statefulset.kubernetes.io/pod-name' in meta['labels']:
        label_selector = {'statefulset.kubernetes.io/pod-name': 'web-1'}
        service_ports = []
        for container in spec['containers']:
            for port in container['ports']:
                service_ports.append(client.models.V1ServicePort(port['containerPort']))
        create_node_port_service(namespace, label_selector, service_ports)
```

```
Traceback (most recent call last):
2020-07-13T18:57:08.449708953Z   File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
2020-07-13T18:57:08.449713832Z     lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
2020-07-13T18:57:08.449717792Z   File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
2020-07-13T18:57:08.449722032Z     **kwargs,
2020-07-13T18:57:08.449725562Z   File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 148, in invoke
2020-07-13T18:57:08.449729632Z     await asyncio.shield(future)  # slightly expensive: creates tasks
2020-07-13T18:57:08.449733333Z   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2020-07-13T18:57:08.449737173Z     result = self.fn(*self.args, **self.kwargs)
2020-07-13T18:57:08.449740653Z   File "main.py", line 16, in create_fn
2020-07-13T18:57:08.449744202Z     service_ports.append(client.models.V1ServicePort(port['containerPort']))
2020-07-13T18:57:08.449747802Z   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_service_port.py", line 63, in __init__
2020-07-13T18:57:08.449751682Z     self.port = port
2020-07-13T18:57:08.449755172Z   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_service_port.py", line 136, in port
2020-07-13T18:57:08.449758753Z     raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501
```
**What you expected to happen**:
Expect to be able to create an array/list of ports
**How to reproduce it (as minimally and precisely as possible)**:
See above
**Anything else we need to know?**:
#401 
**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`) 3.7
- Python client version (`pip list | grep kubernetes`)

**Comment by jicowan** [comment]
has to be port=
