### ISSUE TITLE
Getting AttributeError: module 'kubernetes.client' has no attribute 'select_header_accept'

### ISSUE THREAD

**Issue by danoh-recurly** [kubernetes-client/python#1239]
Getting error when calling list_pod_for_all_namespace
`Listing pods with their IPs:
Traceback (most recent call last):
  File "./get_gcp_gke_app.py", line 144, in <module>
    main()
  File "./get_gcp_gke_app.py", line 141, in main
    get_pod_info(clusters)
  File "./get_gcp_gke_app.py", line 123, in get_pod_info
    pods = v1.list_pod_for_all_namespaces(watch=False )
  File "/Users/dohalloran/src/get_gcp_gke_applications/gcpgke/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 14098, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501
  File "/Users/dohalloran/src/get_gcp_gke_applications/gcpgke/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 14173, in list_pod_for_all_namespaces_with_http_info
    header_params['Accept'] = self.api_client.select_header_accept(
AttributeError: module 'kubernetes.client' has no attribute 'select_header_accept'
`

Requirements.txt file
`google-cloud-container
argparse
google-api-python-client
google-api-core
oauth2client
kubernetes`

Function

`def get_pod_info(clusters):
    config.load_kube_config()
    for cluster in clusters:

        configuration = client.Configuration()

        configuration.host = "https://" + cluster["endpoint"]
        configuration.api_key_prefix['authorization'] = 'Bearer'
        configuration.api_key['authorization'] = token(accessToken)

        with NamedTemporaryFile(delete=False) as cert:
            cert.write(base64.decodebytes(cluster['clusterCaCertificate'].encode()))
            configuration.ssl_ca_cert = cert.name

        print("Cluster ID {0} End Point {1}".format(cluster["name"], cluster["endpoint"]))

        v1 = client.CoreV1Api(client)
        print("Listing pods with their IPs:")
        pods = v1.list_pod_for_all_namespaces(watch=False )`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Run the script.  I have run it multiple times.

**Anything else we need to know?**:
I have looked at the module and found where it was being called.  Everything seems to be there.
`        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/yaml', 'application/vnd.kubernetes.protobuf', 'application/json;stream=watch', 'application/vnd.kubernetes.protobuf;stream=watch'])  # noqa: E501
`
I have also imported client and config as well
`from kubernetes import client, config`

**Environment**:
- Kubernetes version (`kubectl version`):
   = v1.17.4
- OS (e.g., MacOS 10.13.6):
   - 10.15.6
- Python version (`python --version`)
   - Python 3.7.7 
- Python client version (`pip list | grep kubernetes`)
   - kubernetes               11.0.0

**Comment by danoh-recurly** [comment]
was missing a call.  Got it working.
