### ISSUE TITLE
"OSError: [Errno 36] File name too long" When calling any API

### ISSUE THREAD

**Issue by wesleywh** [kubernetes-client/python#1243]
**What happened (please include outputs or screenshots)**:
I'm unable to call the `read_namespaced_config_map` method because it keeps throwing this error on me: 
```
OSError: [Errno 36] File name too long
```
This is using AWS's EKS cluster. I have made an eks cluster and setup the security groups so I can hit it correctly. However, it doesn't work using the python client.

Here is the code I'm using:
```
CLUSTER_NAME = "<place_name_here>"
REGION = "us-west-2"
PROFILE=None

def get_token():
        '''
        Gets the kubernetes token needed to authenticate with the kubernetes api
        '''
        EKS_HEADER = 'x-k8s-aws-id'
        EKS_PREFIX = 'k8s-aws-v1.'
        STS_ACTION = 'Action=GetCallerIdentity&Version=2011-06-15'
        EXPIRES = 60

        session = boto3.session.Session()

        client = session.client('sts', region_name=REGION)
        service_id = client.meta.service_model.service_id

        signer = RequestSigner(
            service_id,
            session.region_name,
            'sts',
            'v4',
            session.get_credentials(),
            session.events
        )

        params = {
            'method': 'GET',
            'url': 'https://sts.{}.amazonaws.com/?{}'.format(REGION, STS_ACTION),
            'body': {},
            'headers': {
                EKS_HEADER: CLUSTER_NAME
            },
            'context': {}
        }

        signed_url = signer.generate_presigned_url(
            params,
            region_name=REGION,
            expires_in=EXPIRES,
            operation_name=''
        )

        base64_url = base64.urlsafe_b64encode(
            signed_url.encode('utf-8')).decode('utf-8')

        # remove any base64 encoding padding:
        return EKS_PREFIX + re.sub(r'=*', '', base64_url)

def get_client(client_type):
        if PROFILE:
            session = boto3.Session(profile_name=PROFILE)
            client = session.client(client_type, region_name=REGION)
        else:
            client = boto3.client(client_type, region_name=REGION)
        return client

# Get cluster details
_eks_client = get_client("eks")
cluster = _eks_client.describe_cluster(name=CLUSTER_NAME)
cluster_certificate = cluster["cluster"]["certificateAuthority"]["data"]
cluster_endpoint = cluster["cluster"]["endpoint"]

# Configure kubernetes config
configuration = client.Configuration()
configuration.verify_ssl=True
configuration.assert_hostname = False
configuration.ssl_ca_cert=cluster_certificate
configuration.host = cluster_endpoint
configuration.api_key = {"authorization": "Bearer " + get_token()}
configuration.debug = True

with client.ApiClient(configuration) as api_client:
    api_instance = client.CoreV1Api(api_client)
    api_response = api_instance.read_namespaced_config_map("aws-auth", "kube-system")
```

**What you expected to happen**:
V1ConfigMap object to be returned and not error out on me

**How to reproduce it (as minimally and precisely as possible)**:
I have posted the exact code you can use above. You just need to specify an eks cluster stack name

**Anything else we need to know?**:
Here is the stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 336, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
OSError: [Errno 36] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 338, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 36] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eks/cluster/main.py", line 104, in <module>
    "Name": "xva-dev-wes-cluster"
  File "/home/wes/dev/aws-lambda/eks/cluster/logic.py", line 222, in set_kubectl_users
    conf_map = kube.get_config_map("aws-auth","default")
  File "/home/wes/dev/aws-lambda/eks/cluster/kubectl.py", line 240, in get_config_map
    api_response = api_instance.read_namespaced_config_map(name, namespace, pretty=True, exact=True, export=True)
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 18390, in read_namespaced_config_map
    (data) = self.read_namespaced_config_map_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 18481, in read_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 366, in request
    headers=headers)
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 241, in GET
    query_params=query_params)
  File "/home/wes/.local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 214, in request
    headers=headers)
  File "/usr/lib/python3.7/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/lib/python3.7/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<redacted>', port=443): Max retries exceeded with url: /api/v1/namespaces/kube-system/configmaps/aws-auth?pretty=True&exact=True&export=True (Caused by SSLError(OSError(36, 'File name too long')))
```
**Environment**:
- Kubernetes version (`kubectl version`): version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g., MacOS 10.13.6): Fedora release 31 (Thirty One)
- Python version (`python --version`): Python 3.7.6
- Python client version (`pip list | grep kubernetes`): 11.0.0

**Comment by wesleywh** [comment]
So I have been trying to figure this out since yesterday and here is what I have so far.

prior to this code:
```
with client.ApiClient(self.configuration) as api_client:
```
the `configuration.cert_file` is `None`. When it reaches the `RESTClientObject` class its too big to output. So I'm currently trying to track down how this is getting set.

**Comment by wesleywh** [comment]
Okay I think it's because I'm using the the following line wrong:
```
_eks_client = get_client("eks")
...
...
cluster_certificate = cluster["cluster"]["certificateAuthority"]["data"]
...
...
configuration.ssl_ca_cert=cluster_certificate
```
I should really be referencing a file with that cluster certificate right? I think I need to write it to a file first but just writing that text to a .pem or .crt file isn't enough. I think I need to format it in a specific way maybe. Not sure yet, still debugging.

**Comment by wesleywh** [comment]
Hey hey! I think I figured it out. I needed this:
```
_eks_client = get_client("eks")
cluster_certificate = cluster["cluster"]["certificateAuthority"]["data"]
with open("/tmp/cluster_ca_cert.pem", "w") as certfile:
            certfile.write(base64.b64decode(cluster_ca_certificate).decode("utf-8"))
...
...
configuration.ssl_ca_cert=cluster_certificate
```
Now I can at least make the call. Still getting errors but I think it's just more of me passing in the wrong information to some of my calls. So I'm going to close this for now.

**Comment by thallesdaniell** [comment]
I extracted the data into this file and saved it as cert.crt and referenced it.

`cat .kube/config | grep certificate-authority-data | cut -f2 -d: | xargs | base64 --decode`
