### ISSUE TITLE
404 error when scheduling a batch job.

### ISSUE THREAD

**Issue by alextaran1996** [kubernetes-client/python#1246]
**What happened (please include outputs or screenshots)**:
```
Traceback (most recent call last):
  File "templating.py", line 181, in <module>
    namespace = nft_tests_namespace
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/api/batch_v1_api.py", line 58, in create_namespaced_job
    (data) = self.create_namespaced_job_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/api/batch_v1_api.py", line 149, in create_namespaced_job_with_http_info
    collection_formats=collection_formats)
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 388, in request
    body=body)
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 278, in POST
    body=body)
  File "/home/alex/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/html; charset=us-ascii', 'Server': 'Microsoft-HTTPAPI/2.0', 'Date': 'Fri, 04 Sep 2020 10:44:45 GMT', 'Connection': 'close', 'Content-Length': '315'})
HTTP response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>
```

**What you expected to happen**:
Scheduled job.

**How to reproduce it (as minimally and precisely as possible)**:
 This was done based on examples from git: https://github.com/kubernetes-client/python/blob/master/examples/job_crud.py
```
config.load_kube_config()
batch_v1 = client.BatchV1Api()
job = create_job_object(jmeter_execution_command)
api_response = batch_v1.create_namespaced_job(
        body = job,
        namespace = nft_tests_namespace
)
print(batch_v1)
# print("Job created. status='%s'" % str(api_response.status))
```

**Environment**:
- Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.15.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Python version (`python --version`): `Python 3.6.9`

- Python client version (`pip list | grep kubernetes`): `11.0.0`

**Comment by palnabarun** [comment]
Hi @alextaran1996 :wave:, looking at your error logs, a few questions came to my mind:
1. Are you able to perform the same using kubectl?
2. Is there a proxy sitting between wherever you are running the code and the Kubernetes cluster's API server?

**Comment by alextaran1996** [comment]
Sorry was the issue from my side. Authentication was placed in the wrong part of the script.
