### ISSUE TITLE
CustomObjectsApi get HTTP response body: 404 page not found with Spark-Operator

### ISSUE THREAD

**Issue by Focke-Wulf** [kubernetes-client/python#1316]
**What happened (please include outputs or screenshots)**:

first of all i am using configuration like 
```
configuration = client.Configuration()
configuration.host = "https://{}:443".format(KUBERNETES_SERVICE_HOST)
configuration.verify_ssl = True
configuration.ssl_ca_cert="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
configuration.api_key = {"authorization": " Bearer " + TOKEN}
client.Configuration.set_default(configuration)
api_client = client.ApiClient(configuration)
```
every thing works fine with other k8s API without CRD.

when i am trying to use python k8s api to manage my spark-operator workflow

```
with client.ApiClient(configuration) as api_client:
        api_instance = client.CustomObjectsApi(api_client)
        api_response = api_instance.list_cluster_custom_object(group="sparkoperator.k8s.io",version='v1beta2' \
                           ,plural='SparkApplication')
        print(api_response)
```

**What you expected to happen**:
i got 

```
Traceback (most recent call last):
  File "/config/workspace/kuba/__init__.py", line 136, in <module>
    main()
  File "/config/workspace/kuba/__init__.py", line 133, in main
    ,plural='SparkApplication')
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api/custom_objects_api.py", line 1940, in list_cluster_custom_object
    return self.list_cluster_custom_object_with_http_info(group, version, plural, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api/custom_objects_api.py", line 2077, in list_cluster_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '29a0d5af-429b-4f54-b97b-63078ed5d3a2', 'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 13 Nov 2020 04:54:13 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```
i have no idea it still using HTTP to access the k8s api server?
or anyother problems?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):  1.8
- OS : Ubuntu 18.04
- Python version (`python --version`): 3.7.4
- Python client version (`pip list | grep kubernetes`): kubernetes (12.0.0)

**Comment by Focke-Wulf** [comment]
i am dumb plural is wrong

**Comment by kyprifog** [comment]
For anyone else that stumbles on this like I did and don't know what to specify as plural because it seems to have changed for spark-operator you can get it by running:

```
kubectl api-resources | grep spark
sparkapplications                 sparkapp            sparkoperator.k8s.io           true         SparkApplication
```
