### ISSUE TITLE
Ingress API is now GA with k8s 1.19 and no beta anymore

### ISSUE THREAD

**Issue by bpereto** [kubernetes-client/python#1330]
**What happened (please include outputs or screenshots)**:
kubernetes client model does not find "V1/Ingress"

**What you expected to happen**:
v1/ingress works on k8s 1.19

**How to reproduce it (as minimally and precisely as possible)**:
Use/Testing with #989 against k8s 1.19:
```
Lookup info: {'group': 'Networking', 'version': 'v1', 'kind': 'ingress', 'items_kind': None, 'fcn_to_call': 'NetworkingV1Api', 'fnc_lookup': None}
Traceback (most recent call last):
  File "k8s-loader.py", line 35, in <module>
    o = utils.load_from_dict(data=obj, verbose=True)
  File "/home/beni/.local/lib/python3.8/site-packages/kubernetes/utils/deserialize.py", line 279, in load_from_dict
    raise FailToLoadError(load_exceptions)
kubernetes.utils.deserialize.FailToLoadError:  reason: Failed to find a function to inspect; lookup info: {'group': 'Networking', 'version': 'v1', 'kind': 'ingress', 'items_kind': None, 'fcn_to_call': 'NetworkingV1Api', 'fnc_lookup': None}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6): Linux
- Python version (`python --version`) : Python 3.8.6
- Python client version (`pip list | grep kubernetes`) : kubernetes                    10.0.0-snapshot
testing with  https://github.com/kubernetes-client/python/pull/989

**Comment by palnabarun** [comment]
Hi @bpereto 👋🏽, the Ingress API will be introduced to the client when client version v19.0.0 is released. Ref: https://github.com/kubernetes-client/python/pull/1320.

**Comment by bpereto** [comment]
Released, right ? :)

**Comment by bateau84** [comment]
Any action here?

**Comment by OvervCW** [comment]
When will this be implemented? I'm using this library with a 1.20 cluster and it's already warning about using deprecated APIs.

**Comment by bpereto** [comment]
https://github.com/kubernetes-client/python/pull/1584 is merged.
/close
