### ISSUE TITLE
Client version 1.17 listing pods not working on GKE 1.17

### ISSUE THREAD

**Issue by jamie-34254** [kubernetes-client/python#1336]
**What happened (please include outputs or screenshots)**:
Trying to get a list of pods causes an exception
```
assemblyline@scaler-f6cdd7579-zml45:~$ python3
Python 3.7.9 (default, Nov 25 2020, 03:29:02) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import client, config
>>> print(client.__version__)
17.14.0a1
>>> config.load_incluster_config()
>>> api = client.CoreV1Api()
>>> pods = api.list_pod_for_all_namespaces(field_selector='status.phase==Running', _request_timeout=30)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 16864, in list_pod_for_all_namespaces
    return self.list_pod_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 16981, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 192, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 264, in deserialize
    return self.__deserialize(data, response_type)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 281, in __deserialize
    for sub_data in data]
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 281, in <listcomp>
    for sub_data in data]
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 281, in __deserialize
    for sub_data in data]
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 281, in <listcomp>
    for sub_data in data]
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 641, in __deserialize_model
    instance = klass(**kwargs)
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/models/v1_projected_volume_source.py", line 57, in __init__
    self.sources = sources
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/kubernetes/client/models/v1_projected_volume_source.py", line 103, in sources
    raise ValueError("Invalid value for `sources`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `sources`, must not be `None`
```

**What you expected to happen**:
A list of pods to be returned

**How to reproduce it (as minimally and precisely as possible)**:
Running GKE 1.17.13-gke.1400, setup Python3 pod, `python3 -m pip install kubernetes==17.14.0a1`
```
from kubernetes import client, config
print(client.__version__)
config.load_incluster_config()
api = client.CoreV1Api()
pods = api.list_pod_for_all_namespaces(field_selector='status.phase==Running', _request_timeout=30)
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version: Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1400", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-10-28T09:22:18Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
- OS: Debian 9
- Python version: Python 3.7.9 
- Python client version: 17.14.0a1

**Comment by palnabarun** [comment]
There was an issue with the API definition. This was fixed in https://github.com/kubernetes/kubernetes/pull/94161. The next client release for the patched Kubernetes versions will include the same.
