### ISSUE TITLE
Problem with port-forward

### ISSUE THREAD

**Issue by kk12345-png** [kubernetes-client/python#1340]
I am trying to use connect_get_namespaced_pod_portforward() method to do port-forwarding for one of my pods in minikube environment. It gives error as follows:

```
>>> response = v1.connect_get_namespaced_pod_portforward(name, namespace)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 1142, in connect_get_namespaced_pod_portforward
    return self.connect_get_namespaced_pod_portforward_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 1229, in connect_get_namespaced_pod_portforward_with_http_info
    return self.api_client.call_api(
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/Users/kedarkulkarni/PycharmProjects/zookeeper/venv/lib/python3.9/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 16 Dec 2020 07:38:29 GMT', 'Content-Length': '139'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
```

Could someone please advise on the resolution.

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yliaog** [comment]
what is the python kubernetes client version you're using?

please see this example on how to do port-forwarding in python, https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py

**Comment by roycaihw** [comment]
Closing due to inactivity. Please reopen if needed

/close
