### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'openapi_types'

### ISSUE THREAD

**Issue by chester0502** [kubernetes-client/python#1350]
**What happened (please include outputs or screenshots)**:

from kubernetes import client, config
import yaml
import pprint
from kubernetes.client.rest import ApiException

config.load_kube_config("/home/test/kubeconfig.yaml")

v1 = client.CoreV1Api()

yamlFile = "/home/test/test.yaml"

with open(yamlFile, "rb") as f:
        yamlVal = yaml.safe_load_all(f)
        print(type(yamlVal))
        print(yamlVal)
        try:
                rtn = v1.create_namespaced_pod(body = yamlVal, namespace = "default")
                pprint(rtn)
        except ApiException as e:
                print("Create pod - Exception when calling CoreV1Api->create_namespaced_pod: %s", e)

Traceback (most recent call last):
  File "createPod.py", line 17, in <module>
    rtn = v1.create_namespaced_pod(body = yamlVal, namespace = "default")
  File "/usr/local/python3/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/usr/local/python3/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7429, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/python3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/python3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 170, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/usr/local/python3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 238, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'generator' object has no attribute 'openapi_types'

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.18.6
- Python version (`python --version`) 3.7.2
- Python client version (`pip list | grep kubernetes`) 12.0.1

**Comment by riceluxs1t** [comment]
I confirm that in 
```
Python version: 3.7.6
Python client version: 12.0.1
Kubernetes version : v1.18.9
```

I have the same issue for both V1ConfigMap and V1Secret objects
```
self.client.create_namespaced_secret(
    self.namespace,
    V1Secret(metadata=client.V1ObjectMeta(name=secret_name), string_data=user_secrets),
)
```

```
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api/core_v1_api.py", line 8166, in create_namespaced_secret
[setup : setup]     return self.create_namespaced_secret_with_http_info(namespace, body, **kwargs)  # noqa: E501
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api/core_v1_api.py", line 8275, in create_namespaced_secret_with_http_info
[setup : setup]     collection_formats=collection_formats)
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 353, in call_api
[setup : setup]     _preload_content, _request_timeout, _host)
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 170, in __call_api
[setup : setup]     body = self.sanitize_for_serialization(body)
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 242, in sanitize_for_serialization
[setup : setup]     for key, val in six.iteritems(obj_dict)}
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 242, in <dictcomp>
[setup : setup]     for key, val in six.iteritems(obj_dict)}
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 222, in sanitize_for_serialization
[setup : setup]     for sub_obj in obj]
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 222, in <listcomp>
[setup : setup]     for sub_obj in obj]
[setup : setup]   File "/tekton/home/.pex/installed_wheels/9ace20da04f9a66fbbc8fb678aab5d1702ac49da/kubernetes-12.0.1-py2.py3-none-any.whl/kubernetes/client/api_client.py", line 238, in sanitize_for_serialization
[setup : setup]     for attr, _ in six.iteritems(obj.openapi_types)
[setup : setup] AttributeError: 'Secret' object has no attribute 'openapi_types'
```

**Comment by chester0502** [comment]
The problem is solved. Need to extract the type object from yaml file and process it separately.

**Comment by muasif80** [comment]
Hello @chester0502 

I am also getting same error.

I am not sure what to do here at all?

We need to put all these configs in yaml file and load it as yaml and then process or what?

**Comment by mbhainsdev** [comment]
@jordyvaneijk how are you parsing the yaml try giving body as simple  json
`my_resouces = {
            "apiVersion": "customcrd.co/v1",
            "kind": "mycustomcrd",
            "metadata": {
                "name": "customdata"
            },
            "spec": {
                "version": "8.1.1",
                "nodeSets": [
                {
                    "name": "default",
                    "count": 2,
                    "config": {
                    "node.store.allow_mmap": "false"
                    }
                }
                ]
            }
            }`

**Comment by michailbrynard** [comment]
I get the same error when creating an ingress using `kubernetes==24.2.0` with:
```
api_instance = NetworkingV1Api()
body = V1Ingress(
    api_version='networking.k8s.io/v1',
    kind='Ingress',
    metadata=V1ObjectMeta(
        name=ingress_name,
        namespace=namespace,
        annotations={'kubernetes.io/ingress.class: nginx',
                     'cert-manager.io/cluster-issuer: letsencrypt'}),
    spec=V1IngressSpec(
        rules=[V1IngressRule(
            host=domain,
            http=V1HTTPIngressRuleValue(
                paths=[V1HTTPIngressPath(
                    path_type="ImplementationSpecific",
                    backend=V1IngressBackend(
                        service=V1IngressServiceBackend(
                            port=V1ServiceBackendPort(
                                number=80,
                            ),
                            name=service-name
                        )
                    )
                )]
            )
        )],
        tls=[V1IngressTLS(
            hosts=[domain],
            secret_name='{}-tls'.format(
                ingress_name')
        )]
    )
)
api_instance.create_namespaced_ingress(namespace, body)
```
The above results in the error `'set' object has no attribute 'openapi_types'`

I solved it by switching to specifying the ingress using json:

```
api_instance = NetworkingV1Api()
body = {
                    "apiVersion": "networking.k8s.io/v1",
                    "kind": "Ingress",
                    "metadata": {
                        "annotations": {
                            "kubernetes.io/ingress.class": "nginx",
                            "cert-manager.io/cluster-issuer": "letsencrypt"
                        },
                        "name": ingress_name,
                        "namespace": namespace
                    },
                    "spec": {
                        "rules": [
                            {
                                "host": domain,
                                "http": {
                                    "paths": [
                                        {
                                            "backend": {
                                                "service": {
                                                    "name": service_name,
                                                    "port": {
                                                        "number": 80
                                                    }
                                                }
                                            },
                                            "pathType": "ImplementationSpecific"
                                        }
                                    ]
                                }
                            }
                        ],
                        "tls": [
                            {
                                "hosts": [
                                    domain
                                ],
                                "secretName": ingress_name
                            }
                        ]
                    }
                    }
 api_instance.create_namespaced_ingress(namespace, body)
 ```
