### ISSUE TITLE
SSL error occurs when using client-certificate-data/client-key-data authentication in kubeconfig

### ISSUE THREAD

**Issue by wangao1236** [kubernetes-client/python#1355]
**What happened (please include outputs or screenshots)**:

I used the demo code to test kubeconfig:
```
# !/usr/bin/python3
# -*- coding: utf-8 -*-

from kubernetes import client, config
config.kube_config.load_kube_config(config_file="/root/.kube/config-bak")
config.verify_ssl=False
print (1)
v1 = client.CoreV1Api()
print (2)
ret = v1.list_pod_for_all_namespaces(watch=False)
print (3)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))
print (4)
```
However, the following error occurred:
```
1
2
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 397, in ssl_wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3554)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "k8s.py", line 10, in <module>
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 16864, in list_pod_for_all_namespaces
    return self.list_pod_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 16981, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 216, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='********', port=443): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:3554)'),))
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

When I use client-certifate instead of token in kubeconfig file, the error mentioned above occurs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.18.4
- OS (e.g., MacOS 10.13.6): CentOS Linux release 7.2
- Python version (`python --version`): Python 3.6.8
- Python client version (`pip list | grep kubernetes`): kubernetes-17.14.0a1

**Comment by wangao1236** [comment]
There is something wrong with the format of my certificate, I have found the problem, thank you~I will close this issue.

**Comment by buptbubble** [comment]
What's wrong with your format? I have exactly the same problem with you.

**Comment by wangao1236** [comment]
> What's wrong with your format? I have exactly the same problem with you.

Previously, my PEM file began with "-----BEGIN PRIVATE KEY-----", and it still worked when I used client-go, but not worked when I tried python-client. After I modified to start with "-----BEGIN RSA PRIVATE KEY-----", it worked.
Maybe you can learn more by following the link below: https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key
