### ISSUE TITLE
read_namespaced_pod failed with urllib3.exceptions.MaxRetryError

### ISSUE THREAD

**Issue by phracek** [kubernetes-client/python#1361]
**What happened (please include outputs or screenshots)**:
On OpenShift 4.4 I have a POD from which I would like to create and start another POD.
The starting POD is done in OpenShift and not from my OS.

The traceback is following:
```bash
[2021-01-28 12:09:23,992: DEBUG/ForkPoolWorker-1] Setup kubernetes
[2021-01-28 12:09:23,993: INFO/ForkPoolWorker-1] Creating POD in project namespace core-services-ocp
[2021-01-28 12:09:23,993: DEBUG/ForkPoolWorker-1] command: ['oc', 'whoami', '-t']
[2021-01-28 12:09:24,479: DEBUG/ForkPoolWorker-1] OpenShift API token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlhaVlc3YnFrZ1BaSllHSkpoNnVLenpTQlE1X3lrcEJzVndHWUdJclVDVEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjb3JlLXNlcnZpY2VzLW9jcCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJiZXRrYS10b2tlbi1zaG5nYiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJiZXRrYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk4ZmUwNjBlLWQ2NWMtNDYwZC04NmE2LTI2YTZjY2IxNzdjOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjb3JlLXNlcnZpY2VzLW9jcDpiZXRrYSJ9.bwXQmS5qpJfGr3DSt0bq_7TRCsx9AERAK-JRApyjQQ7nwBB5ebDH-ARbptcOL-DzC7J3HgvqQrA7MbUWXAbStQaa06bIXaiHXUA2J9H4Xl3kWDJpLuEb5Dvp8VaRXwuD4ANoAY1NEhcGGBDw-__ZBHAG-FkVK3H2RJXf65IClfBOdZ6KMJwTjiuatK_EmnUK1DtmHl9VW3reyNR0y9VG5l7jhmHi4hKqC0Wr0nazxl-5wT5X_tio-DvJrWrGaIQXTZ-62LKxB0rsZ6BvxXDdczGJNg3m8fHE6QhHRL6kMkoWYMZ0BKeUYnfN3BKmY82yIVXJQB7QEX_5iUCqk5Jj4Q
[2021-01-28 12:09:24,555: WARNING/ForkPoolWorker-1] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f083e7e9390>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/core-services-ocp/pods/betka-cwt-latest-20210128120920-s2i-python-container-deployment
[2021-01-28 12:09:24,556: WARNING/ForkPoolWorker-1] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f083e6ed150>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/core-services-ocp/pods/betka-cwt-latest-20210128120920-s2i-python-container-deployment
[2021-01-28 12:09:24,556: WARNING/ForkPoolWorker-1] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f083e6cb350>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/core-services-ocp/pods/betka-cwt-latest-20210128120920-s2i-python-container-deployment
```
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f083e6ed8d0>: Failed to establish a new connection: [Errno 111] Connection refused
```
**What you expected to happen**:
POD is created and started.

**How to reproduce it (as minimally and precisely as possible)**:
My code is here: https://github.com/sclorg/betka/blob/master/betka/openshift.py

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 
- OS (e.g., MacOS 10.13.6): MacOS 11.0.1
- Python version (`python --version`)
- Python client version (`pip list | grep kubernetes`)

**Comment by fabianvf** [comment]
@phracek is your `Configuration` object pointing to the proper URL for the API? Usually when running from a pod in the cluster one would use the `kubernetes.config.load_incluster_config` to pull the information from the mounted secrets. Looking at the error message my guess would be that it's just not pointing at the API server (and thus cannot get a connection)

**Comment by phracek** [comment]
See my code here:

```python
from kubernetes import config, client
from kubernetes.client.rest import ApiException

class OpenshiftDeployer(object):

    @property
    def kubernetes_api(self) -> client.CoreV1Api:
        if not self._kubernetes_api:
            self.api_token = run_cmd(["oc", "whoami", "-t"], return_output=True).strip()
            logger.debug(f"OpenShift API token: {self.api_token}")
            configuration = client.Configuration()
            configuration.api_key["authorization"] = self.api_token
            configuration.api_key_prefix["authorization"] = "Bearer"
            self._kubernetes_api = client.CoreV1Api(client.ApiClient(configuration))
        return self._kubernetes_api

    def setup_kubernetes(self):
        logger.debug("Setup kubernetes")
        config.load_incluster_config()

    def deploy_pod(self) -> bool:
        logger.info(f"Creating POD {self.pod_name} in project namespace {self.project_name}")
        resp = None
        try:
            resp = self.kubernetes_api.read_namespaced_pod(
                name=self.pod_name, namespace=self.project_name
            )
        except ApiException as e:
            logger.info(e.status)
            if e.status != 404:
                logger.error(f"Unknown error: {e!r}")
                raise BetkaDeployException
```

**Comment by phracek** [comment]
One point. On OpenShift 3.11 all worked properly. Tomorrow I will test on OpenShift 4.3.
This part of the code does not work on OpenShift 4.5.

**Comment by phracek** [comment]
With this part of the code, I am able to create a PR.

```python
    @staticmethod
    def kubernetes_api() -> CoreV1Api:
        configuration = Configuration()
        load_incluster_config(client_configuration=configuration)
        return CoreV1Api(ApiClient(configuration=configuration))
```
