### ISSUE TITLE
The skip SSL checks option is NOT working

### ISSUE THREAD

**Issue by ohadm2** [kubernetes-client/python#1512]
**What happened (please include outputs or screenshots)**:
The included script is not working.

**What you expected to happen**:
The included script should work.

**How to reproduce it (as minimally and precisely as possible)**:
Use a K8s cluster with self signed certs install on the api server.

**Anything else we need to know?**:
Error details:

user@ubuntu:~/python-kubernetes-module-example$ python3 example.py 
{'host': 'http://localhost', 'temp_folder_path': None, 'api_key': {}, 'api_key_prefix': {}, 'refresh_api_key_hook': None, 'username': None, 'password': None, 'discard_unknown_keys': False, 'logger': {'package_logger': <Logger client (WARNING)>, 'urllib3_logger': <Logger urllib3 (WARNING)>}, '_Configuration__logger_format': '%(asctime)s %(levelname)s %(message)s', 'logger_formatter': <logging.Formatter object at 0x7f48aea18f70>, 'logger_stream_handler': None, 'logger_file_handler': None, '_Configuration__logger_file': None, '_Configuration__debug': False, 'verify_ssl': False, 'ssl_ca_cert': None, 'cert_file': None, 'key_file': None, 'assert_hostname': None, 'connection_pool_maxsize': 20, 'proxy': None, 'proxy_headers': None, 'safe_chars_for_path_param': '', 'retries': None, 'client_side_validation': True}
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/projects/k8s-related/projects/python-kubernetes-module-example/example.py", line 11, in <module>
    config.load_kube_config(client_configuration=configuration)
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 822, in load_kube_config
    loader.load_and_set(client_configuration)
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 589, in load_and_set
    self._load_authentication()
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 287, in _load_authentication
    if self._load_auth_provider_token():
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 306, in _load_auth_provider_token
    return self._load_oid_token(provider)
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 410, in _load_oid_token
    self._refresh_oidc(provider)
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 444, in _refresh_oidc
    response = client.request(
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/user/.local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my-correct-host', port=my-correct-port): Max retries exceeded with url: /oauth/token/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

Script Content:

from kubernetes import client,config

configuration = client.Configuration()

configuration.verify_ssl = False
configuration.client_side_validation = False
configuration._Configuration__debug = True

print(configuration.__dict__)

config.load_kube_config(client_configuration=configuration)

v1 = client.CoreV1Api()

print("Listing pods with their IPs:")

ret = v1.list_pod_for_all_namespaces(watch=False)

for i in ret.items:
	print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))
	
[ssl-err.txt](https://github.com/kubernetes-client/python/files/6928968/ssl-err.txt)
[example.py.txt](https://github.com/kubernetes-client/python/files/6928970/example.py.txt)

**Environment**:
- Kubernetes Vmware's TKGI implementation.

**Comment by roycaihw** [comment]
When calling `load_kube_config` with `client_configuration`, the method sets the provided `client_configuration` without setting the [global default](https://github.com/kubernetes-client/python-base/blob/dd15ac62636c9ccf1493a02a0bdd5e3a8678c413/config/kube_config.py#L817-L822). On the other hand, the API client [uses the global default](https://github.com/kubernetes-client/python/blob/6b01c95e1673c0787d3d688b361bfd995d62dd98/kubernetes/client/api_client.py#L70-L71) when no configuration is provided. 

To use the configuration with SSL checks skipped, could you try
```
v1 = client.CoreV1Api(api_client=client.ApiClient(configuration=configuration))
```

**Comment by roycaihw** [comment]
Closing due to inactivity. Please feel free to reopen if needed

/remove-lifecycle stale
/close
