### ISSUE TITLE
AttributeError: module 'kubernetes.client.models.v1_scale' has no attribute 'openapi_types'

### ISSUE THREAD

**Issue by mofanke** [kubernetes-client/python#1522]
**What happened (please include outputs or screenshots)**:
```Traceback (most recent call last):
  File "test_k8s.py", line 41, in <module>
    api_response = api_instance.patch_namespaced_deployment_scale(name, namespace, body)
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 4667, in patch_namespaced_deployment_scale
    return self.patch_namespaced_deployment_scale_with_http_info(name, namespace, body, **kwargs)  # noqa: E501
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 4778, in patch_namespaced_deployment_scale_with_http_info
    return self.api_client.call_api(
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 170, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 241, in sanitize_for_serialization
    return {key: self.sanitize_for_serialization(val)
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 241, in <dictcomp>
    return {key: self.sanitize_for_serialization(val)
  File "/data/venv/locust/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 238, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: module 'kubernetes.client.models.v1_scale' has no attribute 'openapi_types'
```

**What you expected to happen**:
exec ok
**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md#patch_namespaced_deployment_scale

just as the example says

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6):

ubuntu

- Python version (`python --version`)

Python 3.8.9
- Python client version (`pip list | grep kubernetes`)

kubernetes         17.17.0

**Comment by mofanke** [comment]
sorry my code has error
