### ISSUE TITLE
Max retries exceeded. Failed to establish a new connection: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by arthemis911222** [kubernetes-client/python#1535]
**What happened (please include outputs or screenshots)**:

```
urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kube-prom-reload.py", line 77, in 
  File "kube-prom-reload.py", line 52, in main
  File "kube_monitor_api.py", line 364, in get_pods_from_sts
  File "kube_monitor_api.py", line 36, in get_label_from_sts
  File "kubernetes/client/api/apps_v1_api.py", line 7105, in read_namespaced_stateful_set
  File "kubernetes/client/api/apps_v1_api.py", line 7200, in read_namespaced_stateful_set_with_http_info
  File "kubernetes/client/api_client.py", line 348, in call_api
  File "kubernetes/client/api_client.py", line 180, in __call_api
  File "kubernetes/client/api_client.py", line 373, in request
  File "kubernetes/client/rest.py", line 239, in GET
  File "kubernetes/client/rest.py", line 212, in request
  File "urllib3/request.py", line 75, in request
  File "urllib3/request.py", line 97, in request_encode_url
  File "urllib3/poolmanager.py", line 336, in urlopen
  File "urllib3/connectionpool.py", line 752, in urlopen
  File "urllib3/connectionpool.py", line 752, in urlopen
  File "urllib3/connectionpool.py", line 752, in urlopen
  File "urllib3/connectionpool.py", line 724, in urlopen
  File "urllib3/util/retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxx-xxx-xxx', port=xxx): Max retries exceeded with url: /apis/apps/v1/namespaces/monitoring/statefulsets/prometheus(Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))
[1869] Failed to execute script 'kube-prom-reload' due to unhandled exception!
```

**What you expected to happen**:
execute success

**How to reproduce it (as minimally and precisely as possible)**:
1. load config file
2. get pod list from statesfulset by matchLables
3. exec prometheus hot reload on pod list

```python
...

def init_config(config_file):
    configfile = config_file
    config.load_kube_config(config_file=configfile)
    try:
        c = Configuration().get_default_copy()
    except AttributeError:
        c = Configuration()
        c.assert_hostname = False #line 52 in error infor from screenshots
    Configuration.set_default(c)

    # “KubeMonitorApi” include core_v1 and apps_v1
    kube_monitor= KubeMonitorApi()

    return kube_monitor

def main():

    for k in kube_list:
        c_file = k8s_config[k]
        kube_monitor = init_config(c_file)

        for sts_name in sts_list:
            # get pod list from statesfulset by matchLabels
            pod_list = kube_monitor.get_pods_from_sts(sts_name,namespace)

            if pod_list == None or len(pod_list) <= 0:
                continue

            # prometheus hot reload
            ...
            # prometheus hot reload

    return

```

**Anything else we need to know?**:
1. When I exec my script on k8s cluster, sometimes it success, but sometimes it failed(same statefuleset, same k8s cluster). I want to know why and how to solve it. 
2. I test to exec script on multi cluster or one cluster(which return error), sometimes success, sometimes failed.

**Environment**:
- Kubernetes version (`kubectl version`): v1.16.3
- OS: Ubuntu 14.04.6 LTS
- Python version: python3.8
- Python client version (`pip list | grep kubernetes`):17.17.0

**Comment by roycaihw** [comment]
Could you try `kubectl exec` and see if that works? 

> [Errno -2] Name or service not known

This sounds like a connection flake rather than a client issue
