### ISSUE TITLE
cannot watch resource "configmaps" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by nevosial** [kubernetes-client/python#1647]
**What happened (please include outputs or screenshots)**:
Trying to build a container that watches configmap resource. However , when run as pod errors out with the 

```
Traceback (most recent call last):
  File "src/dash_watch.py", line 93, in <module>
    main()
  File "src/dash_watch.py", line 40, in main
    for event in w.stream(v1.list_config_map_for_all_namespaces, label_selector=label_selector, timeout_seconds=0):
  File "/usr/local/lib/python3.8/site-packages/kubernetes/watch/watch.py", line 163, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 13827, in list_config_map_for_all_namespaces
    return self.list_config_map_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 13934, in list_config_map_for_all_namespaces_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1b3f8c86-73ba-45b9-bb23-2863075febde', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 10 Dec 2021 03:39:18 GMT', 'Content-Length': '310'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \\"system:serviceaccount:cloudops:cm-watcher\\" cannot watch resource \\"configmaps\\" in API group \\"\\" at the cluster scope","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}\n'
```

Using the following rbac configs.
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-watcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cm-watcher
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-watcher
subjects:
  - kind: ServiceAccount
    name: cm-watcher
roleRef:
  kind: ClusterRole
  name: cm-watcher
  apiGroup: rbac.authorization.k8s.io
```

**What you expected to happen**:
Be able to list and watch the configmaps.

**How to reproduce it (as minimally and precisely as possible)**:
Create a simple pod that uses the watcher like so
`event in w.stream(v1.list_config_map_for_all_namespaces, label_selector=label_selector, timeout_seconds=0):`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):  1.20
- OS (e.g., MacOS 10.13.6): Ubuntu
- Python version (`python --version`) : Python 3.8.12
- Python client version (`pip list | grep kubernetes`) : kubernetes        20.13.0

**Comment by nevosial** [comment]
This was resolved by adding the service account in the same namespace as the pod.
