### ISSUE TITLE
Installation failing due to mismatch of Python and PyYAML

### ISSUE THREAD

**Issue by mk46** [kubernetes-client/python#1736]
**What happened (please include outputs or screenshots)**:
Installation failing due to mismatch of python and PyYAML
**What you expected to happen**:
There are two possible solutions:
1) Add Python=>3.6 as per https://pypi.org/project/PyYAML/   or
2) Pin PyYAML to [5.4.1](https://pypi.org/project/PyYAML/5.4.1/) 
**How to reproduce it (as minimally and precisely as possible)**:
When using python 2.17.7, following https://github.com/kubernetes-client/python#installation 
and getting the below error on `python setup.py install` 
```
Best match: PyYAML 6.0                                                                                                                                
Processing PyYAML-6.0.tar.gz                                                                                                                          
Writing /tmp/easy_install-NBmaNH/PyYAML-6.0/setup.cfg                                                                                                 
Running PyYAML-6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-NBmaNH/PyYAML-6.0/egg-dist-tmp-1tC_Mk                                           
Traceback (most recent call last):                                                                                                                    
  File "setup.py", line 82, in <module>                                                                                                               
    "Programming Language :: Python :: 3.10",                                                                                                         
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup                                                                  
    return distutils.core.setup(**attrs)                                                                                                              
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup                                                                                     
    dist.run_commands()                                                                                                                               
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands                                                                              
    self.run_command(cmd)                                                                                                                             
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command                                                                               
    cmd_obj.run()                                                                                                                                     
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run                                                              
    self.do_egg_install()                                                                                                                             
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install                                                  
    cmd.run()                                                                                                                                         
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.21.0
- OS (e.g., MacOS 10.13.6): Ubuntu 18.04.5
- Python version (`python --version`) : 2.7.17 
- Python client version (`pip list | grep kubernetes`)

**Comment by Akasurde** [comment]
@mk46 Thanks for reporting this issue. You are using Python 2.7.17 version instead of Python 3.6 or above which is a hard requirement for the Pyyaml project. You need to update the Python version and re-try.
