### ISSUE TITLE
utils.create_from_yaml with custom resources: attribute error: kubernetes.client

### ISSUE THREAD

**Issue by cedricfarinazzo** [kubernetes-client/python#1802]
**What happened (please include outputs or screenshots)**:

I'm using Azure Kubernetes Service and Azure Key Vault Provider for Secrets Store CSI Driver to use secrets defined in Azure Key Vault (doc: [here](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver))
To get secrets from Azure Key Vault, I need to create custom resources (example: [here](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#sync-mounted-content-with-a-kubernetes-secret))
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
[...]
```

I'm using ``utils.create_from_yaml`` to apply it but I got the following error:

````
Traceback (most recent call last):
  File "/mnt/c/Users/XXXXX/Documents/MyProject/ZZZZZZZZ/main.py", line 73, in apply_yaml
    utils.create_from_yaml(client, filepath, namespace=NAMESPACE)
  File "/home/XXXXX/.local/lib/python3.9/site-packages/kubernetes/utils/create_from_yaml.py", line 162, in create_from_yaml
    return create_with(yml_document_all)
  File "/home/XXXXX/.local/lib/python3.9/site-packages/kubernetes/utils/create_from_yaml.py", line 146, in create_with   
    created = create_from_dict(k8s_client, yml_document, verbose,
  File "/home/XXXXX/.local/lib/python3.9/site-packages/kubernetes/utils/create_from_yaml.py", line 216, in create_from_dict
    created = create_from_yaml_single_item(
  File "/home/XXXXX/.local/lib/python3.9/site-packages/kubernetes/utils/create_from_yaml.py", line 242, in create_from_yaml_single_item
    k8s_api = getattr(client, fcn_to_call)(k8s_client)
AttributeError: module 'kubernetes.client' has no attribute 'Secrets-storeCsiX-k8sIoV1Api'
````

I don't think this bug is specific to Azure services.

**What you expected to happen**:

The resource to be created. It works fine with ``kubectl apply``

**How to reproduce it (as minimally and precisely as possible)**:

- install the Azure Key Vault provider
- define your SecretProviderClass
- run
```python
from kubernetes import client, config, utils

config.load_kube_config()

utils.create_from_yaml(client, "azure-sync.yml", namespace="your-namespace")
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.22.6
- OS (e.g., MacOS 10.13.6): WSL2 Ubuntu 18.04.5 LTS
- Python version (`python --version`): 3.9.12
- Python client version (`pip list | grep kubernetes`): 23.6.0

**Comment by cedricfarinazzo** [comment]
same issue #1792
