### ISSUE TITLE
Unable to pip install kubernetes on Ubuntu 14

### ISSUE THREAD

**Issue by architlatkar27** [kubernetes-client/python#1847]
**What happened (please include outputs or screenshots)**:
I am trying to install the kubernetes package on an ubuntu 14 machine. It is failing with the following error - 
`Downloading/unpacking kubernetes==9.0.0 (from -r requirements.txt (line 5))
  Downloading kubernetes-9.0.0-py2.py3-none-any.whl (1.4MB): 1.4MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'websocket-client !=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0', 'at', '*,!=0.42.*,>=0.32.0')`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
this can be reproduced by runnning a docker container with ubuntu 14 image. Then install python and pip and try pip install kubernetes
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 9 and above
- OS (e.g., MacOS 10.13.6): ubuntu 14
- Python version (`python --version`): 3.4
- Python client version (`pip list | grep kubernetes`) NA

**Comment by roycaihw** [comment]
> kubernetes==9.0.0 

Please also try the latest versions: https://pypi.org/project/kubernetes/#history
