### ISSUE TITLE
Body is not acccepted as None for patch_certificate_signing_request_approval

### ISSUE THREAD

**Issue by Aman-g99** [kubernetes-client/python#1939]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CertificatesV1Api.md#patch_certificate_signing_request_approval

**Description of the issue (please include outputs or screenshots if possible)**:
```/home/cloud-user/cnSBC/lib64/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.0.0
)/charset_normalizer (2.0.12) doesn't match a supported version!                                                                               RequestsDependencyWarning)
Traceback (most recent call last):
  File "approve_crt.py", line 16, in <module>
    api_response = v1.patch_certificate_signing_request_approval(name, body,  pretty=True)
  File "/home/cloud-user/cnSBC/lib64/python3.6/site-packages/kubernetes/client/api/certificates_v1_api.py", line 928, in patch_certificate_si
gning_request_approval                                                                                                                           return self.patch_certificate_signing_request_approval_with_http_info(name, body, **kwargs)  # noqa: E501
  File "/home/cloud-user/cnSBC/lib64/python3.6/site-packages/kubernetes/client/api/certificates_v1_api.py", line 996, in patch_certificate_si
gning_request_approval_with_http_info                                                                                                            raise ApiValueError("Missing the required parameter `body` when calling `patch_certificate_signing_request_approval`")  # noqa: E501
kubernetes.client.exceptions.ApiValueError: Missing the required parameter `body` when calling `patch_certificate_signing_request_approval`
```

As a workaround -> I tried by adding 
`body = {"metadata": {"namespace": "cnsbcapp-operator-system"}}`

but even then, the approval didn't worked.
Output:
```
/home/cloud-user/cnSBC/lib64/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: u
rllib3 (1.26.12) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!           RequestsDependencyWarning)
{'api_version': 'certificates.k8s.io/v1',
 'kind': 'CertificateSigningRequest',
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2022, 10, 27, 10, 16, 31, tzinfo=tzutc()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'managed_fields': None,
              'name': 'configservice.cnsbcapp-operator-system',
              'namespace': None,
              'owner_references': None,
              'resource_version': '1715067',
              'self_link': None,
              'uid': '72b8e205-8730-47f4-b82f-264173082e54'},
 'spec': {'expiration_seconds': None,
          'extra': None,
          'groups': ['system:masters', 'system:authenticated'],
          'request': 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlZUQ0IvUUlCQURBL01UMHdPd1lEVlFRR
EV6UmpiMjVtYVdkelpYSjJhV05sTG1OdWMySmpZWEJ3TFc5dwpaWEpoZEc5eUxYTjVjM1JsYlM1amJIVnpkR1Z5TG14dlkyRnNNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFOFJ5aTlRQWk0ZmxpNEY4aThuVnJKdE02aU1jMStzOUxwQVBjbC9NZGREMjA0cHVhSmtYUVJ1TVQKaW9PUzRhUHNJemh1Zmk5anRmUHVrN0ltZWtSRGphQmNNRm9HQ1NxR1NJYjNEUUVKRGpGTk1Fc3dTUVlEVlIwUgpCRUl3UUlJNFkyOXVabWxuYzJWeWRtbGpaUzVqYm5OaVkyRndjQzF2Y0dWeVlYUnZjaTF6ZVhOMFpXMHVjM1pqCkxtTnNkWE4wWlhJdWJHOWpZV3lIQkFwcXNNY3dDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdSU3BpdHRDOE0ycE4KZHU3RXdFY3RuRzc4eTdpNHI4N2ZVYkUwaXBydkx0SUNJR2JjUFdNTmpiOXpFUWF0SHJsQjFDUWZDM2ViVk93WAo0dmtWVkFLWmF6T3oKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==',               'signer_name': 'cnsbc.cgbu.oracle.com/configservice',
          'uid': None,
          'usages': ['digital signature', 'key encipherment', 'server auth'],
          'username': 'kubernetes-admin'},
 'status': {'certificate': 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNLZ0F3SUJBZ0lVZkZFeTBBMmtBdUZ
qdkd4Szd3TG5PS0JMNzg4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF4TUpZMjR0ZEdWemRDMHhNQ0FYRFRJeU1UQXlOekV4TURZd01Gb1lEekl4TWpJeApNREF6TVRFd05qQXdXakEvTVQwd093WURWUVFERXpSamIyNW1hV2R6WlhKMmFXTmxMbU51YzJKallYQndMVzl3ClpYSmhkRzl5TFhONWMzUmxiUzVqYkhWemRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUU4UnlpOVFBaTRmbGk0RjhpOG5Wckp0TTZpTWMxK3M5THBBUGNsL01kZEQyMDRwdWFKa1hRUnVNVAppb09TNGFQc0l6aHVmaTlqdGZQdWs3SW1la1JEamFPQndUQ0J2akFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEClZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVaDhpSVZJSkIKNzBLb1QvbklVaU5lMlUwZWhBQXdId1lEVlIwakJCZ3dGb0FVOWE1MXZ0Vk9rV09nUkU5OFJIUmR3Q0pWYXFNdwpTUVlEVlIwUkJFSXdRSUk0WTI5dVptbG5jMlZ5ZG1salpTNWpibk5pWTJGd2NDMXZjR1Z5WVhSdmNpMXplWE4wClpXMHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXeUhCQXBxc01jd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIdkIKM2VYN0d5Z1l6WXJUdEFiR3h3Y2JvcXpHN0NlTlFFN3A0MGxQRFcwTXFSQ21QaFFTai8yZUFWL3E1N2lEVURaZAphc0xHMU9xbUJwYkRUSVgzNitXUm9rTDRKN2V6VXZBVTFmNWF4cUFrTXJVcE1WeFNBWVFMc3pKRkRHTVRjOS9QCjd4OFdaL0k2WUdFUFpXUVJzaGh4RU5LVmhYNThHZGU4dUZVSWpsSU5SVDFiTVFHRlV2N1BLZXErRitDNmpTZm8Kcml5L0w2U0ZqMTNWU0FvOHdXbnU5Rk0vWk55bTh5VytuL0pzM0sxbzU4ckQrK0l3UkFGcitnbEFWYTlDZnNHawpqSDZvQUxuUThSZlJPSFZ5SVNNTG1LYTVmSUtTTTNsT2lJVnRqQ3MzY0l1NGNVL0M4b2VBTGtyZ0ZlYVM1bVh0Cm0waG5mSWZ0MlNZUlIrU2M1VDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K',                                                                                'conditions': None}}

```

**Comment by roycaihw** [comment]
Do you have an example of success using kubectl? Could you provide the details by running the command with `kubectl --v=9`? If we have a example using kubectl, we can achieve the same with this Python client.

**Comment by Aman-g99** [comment]
Hi @roycaihw ,
After deploying the crt and pem file as a secret successfully through client api's.
I used this kubectl command to approve the csr : `kubectl -n "${namespace}" certificate approve "${fqn}"` and it worked fine. (and the output came as expected, csr was approved and I have added the same at the end of the description above.)
But when I am trying to use the api for this APPROVE step - It asks me to send the body as an attribute. According to the documentation, I can send it as NONE but that is not acceptable. So, my question is what should be the format of the body attribute that needs to be passed with `patch_certificate_signing_request_approval(name, body,  pretty=True)` function.
I need to pass just the namespace in the body.
