### ISSUE TITLE
server_side_apply fails from ansible call """Object of type bytes is not JSON serializable"""

### ISSUE THREAD

**Issue by flybyray** [kubernetes-client/python#1960]
**What happened**:

Trying to test `server_side_apply` with ansible task.
Executed a simple ansible task like this:

```yaml
- name: Play1
  hosts: localhost
  become: false
  collections:
    - kubernetes.core
  gather_facts: false
  tasks:
    - name: K8s | manage openshift objects
      kubernetes.core.k8s:
        apply: true
        resource_definition: |-
          apiVersion: v1
          data:
            ca-bundle.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tLi4uLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
          kind: ConfigMap
          metadata:
            name: custom-ca
            namespace: openshift-config
        server_side_apply:
          field_manager: ansible
```

```txt
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Object of type bytes is not JSON serializable
failed: [localhost] (item={'resource_definition': 'apiVersion: v1\ndata:\n  ca-bundle.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tLi4uLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==\nkind: ConfigMap\nmetadata:\n  name: custom-ca\n  namespace: openshift-config\n', 'apply': True, 'server_side_apply': {'field_manager': 'ansible'}}) => changed=false 
  ansible_loop_var: k8s_object
  k8s_object:
    apply: true
    resource_definition: |-
      apiVersion: v1
      data:
        ca-bundle.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tLi4uLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
      kind: ConfigMap
      metadata:
        name: custom-ca
        namespace: openshift-config
    server_side_apply:
      field_manager: ansible
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/user/.ansible/tmp/ansible-tmp-1669809580.6118658-1697337-96283662603503/AnsiballZ_k8s.py", line 107, in <module>
        _ansiballz_main()
      File "/home/user/.ansible/tmp/ansible-tmp-1669809580.6118658-1697337-96283662603503/AnsiballZ_k8s.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/user/.ansible/tmp/ansible-tmp-1669809580.6118658-1697337-96283662603503/AnsiballZ_k8s.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),
      File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 486, in <module>
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 482, in main
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 459, in execute_module
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 807, in execute_module
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 1114, in perform_action
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8sdynamicclient.py", line 45, in apply
      File "/home/user/git-src/tmp/ansible_kubernetes.core.k8s_payload_z8_f7x_c/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/apply.py", line 136, in k8s_apply
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/dynamic/client.py", line 164, in server_side_apply
        return self.request('patch', path, body=body, force_conflicts=force_conflicts, **kwargs)
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
        resp = func(self, *args, **kwargs)
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/dynamic/client.py", line 270, in request
        api_response = self.client.call_api(
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
        return self.__call_api(resource_path, method,
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
        response_data = self.request(
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/client/api_client.py", line 407, in request
        return self.rest_client.PATCH(url,
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/client/rest.py", line 296, in PATCH
        return self.request("PATCH", url,
      File "/home/user/git-src/venv/lib64/python3.9/site-packages/kubernetes/client/rest.py", line 168, in request
        request_body = json.dumps(body)
      File "/usr/lib64/python3.9/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type bytes is not JSON serializable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**What you expected to happen**:
`rc: 0`. No error. It is an object which already exists.

**How to reproduce it**:
idk. I am not quite sure for what the current test case is good for.
There is a different call stack. the `json.dumps`  is executed on a `body` which is several times modified on the call stack.

**Anything else we need to know?**:
Nothing special.

**Environment**:
- Kubernetes version (`oc version`):
    ```txt
    Client Version: 4.11.16
    Kustomize Version: v4.5.4
    Server Version: 4.10.26
    Kubernetes Version: v1.23.5+012e945
    ```
- OS:
    ```txt
    5.15.74.2-microsoft-standard-WSL2
    Oracle Linux Server 8.7
    ```
- Python version (`python --version`):
    ```txt
    Python 3.9.13
    ```
- Python client version (`pip list | grep kubernetes`):
    ```txt
    kubernetes                    25.3.0
    ```

**Comment by flybyray** [comment]
Closing most probably not a bug in kubernetes-client.
The body is passed as `bytes` into kubernetes-client:
https://github.com/ansible-collections/kubernetes.core/blob/2.3.2/plugins/module_utils/apply.py#L134-L137
