### ISSUE TITLE
connect_get_namespaced_pod_exec  API call not working. 

### ISSUE THREAD

**Issue by sdviasat** [kubernetes-client/python#1988]
I get the error below when following the example from the kubernetes-client [repo](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py).

I can use the some of the other rest api commands like "list_pod_for_all_namespaces", 

    exec_command = ["/bin/sh", "-c", command]
    resp = stream(api_instance.connect_get_namespaced_pod_exec,
                  name,
                  namespace,
                  command=exec_command,
                  stderr=True, stdin=False,
                  stdout=True, tty=False)

       Stacktrace:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 519, in websocket_call
            client = WSClient(configuration, url, headers, capture_all)
          File "/usr/local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 65, in __init__
            self.sock = create_websocket(configuration, url, headers)
          File "/usr/local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 485, in create_websocket
            websocket.connect(url, **connect_opt)
          File "/usr/local/lib/python3.9/site-packages/websocket/_core.py", line 250, in connect
            self.handshake_response = handshake(self.sock, url, *addrs, **options)
          File "/usr/local/lib/python3.9/site-packages/websocket/_handshake.py", line 57, in handshake
            status, resp = _get_resp_headers(sock)
          File "/usr/local/lib/python3.9/site-packages/websocket/_handshake.py", line 148, in _get_resp_headers
            raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
        websocket._exceptions.WebSocketBadStatusException: Handshake status 404 Not Found

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/usr/local/lib/python3.9/site-packages/getgauge/executor.py", line 33, in execute_method
            step.impl(*params)
          File "/work/test/gauge/lib_sgn/framework_comp_steps.py", line 33, in get_app_health_status
            container = pod_exec(name,"kubectl describe pod lib-cpp-framework-test")
          File "/work/test/gauge/lib_sgn/framework_comp_steps.py", line 121, in pod_exec
            resp = stream(api_instance.connect_get_namespaced_pod_exec,
          File "/usr/local/lib/python3.9/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
            return api_method(*args, **kwargs)
          File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
            return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
          File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info
            return self.api_client.call_api(
          File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
            return self.__call_api(resource_path, method,
          File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
            response_data = self.request(
          File "/usr/local/lib/python3.9/site-packages/kubernetes/stream/ws_client.py", line 525, in websocket_call
            raise ApiException(status=0, reason=str(e))
        kubernetes.client.exceptions.ApiException: (0)
        Reason: Handshake status 404 Not Found

**Comment by 604691021** [comment]
simple problem:

**Comment by 604691021** [comment]
[2023-01-29 14:23:21][django.channels.server.log_action():189] [INFO] WebSocket HANDSHAKING /webSsh/ [10.3.0.11:5323]
[2023-01-29 14:23:26][django.channels.server.log_action():187] [INFO] WebSocket DISCONNECT /webSsh/ [10.3.0.11:5323]
[2023-01-29 14:23:28][daphne.server.application_checker():296] [ERROR] Exception inside application: (0)
Reason: Handshake status 404 Not Found
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 519, in websocket_call
    client = WSClient(configuration, url, headers, capture_all)
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 65, in __init__
    self.sock = create_websocket(configuration, url, headers)
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 485, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/usr/local/python3/lib/python3.10/site-packages/websocket/_core.py", line 248, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/usr/local/python3/lib/python3.10/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/python3/lib/python3.10/site-packages/websocket/_handshake.py", line 148, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 404 Not Found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 96, in __call__
    return await self.application(scope, receive, send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/routing.py", line 116, in __call__
    return await application(
  File "/usr/local/python3/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/python3/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/python3/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/python3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/consumer.py", line 125, in dispatch
    handler(message)
  File "/usr/local/python3/lib/python3.10/site-packages/channels/generic/websocket.py", line 38, in websocket_connect
    self.connect()
  File "/home/devloper/SRE-Platform/backend/dvadmin/business/私有云/K8S/utils/k8s_ssh.py", line 96, in connect
    self.stream = KubeApi().pod_exec(podName, namespace)
  File "/home/devloper/SRE-Platform/backend/dvadmin/business/私有云/K8S/utils/k8s_ssh.py", line 33, in pod_exec
    cont_stream = stream(api_instance.connect_get_namespaced_pod_exec,
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
    return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info
    return self.api_client.call_api(
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/python3/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 525, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: Handshake status 404 Not Found

**Comment by roycaihw** [comment]
could you try [this example](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py) and see if it works for you?
