### ISSUE TITLE
Use create_namespaced_deployment to apply 999.yaml fail in pod.

### ISSUE THREAD

**Issue by fword-newbie** [kubernetes-client/python#2072]
**What happened (please include outputs or screenshots):**
I use create_namespaced_deployment to apply 999.yaml in pod "cloneyaml".

```
root@cloneyaml:/cloneyaml# ls
999.yaml  applyv2.py

```

**here is my code "applyv2.py":**
```
from flask import Flask, request
from kubernetes import client, config
import yaml
import os

app = Flask(__name__)

def main():
    config.load_incluster_config()
    v1 = client.CoreV1Api()

k8s_client = client.ApiClient()

def deploy_yaml(yaml_file):
    with open(yaml_file, 'r') as file:
        yaml_content = yaml.load_all(file,yaml.FullLoader)
        yaml_content = list(yaml_content)[0]
    api_instance = client.AppsV1Api(k8s_client)
    api_instance.create_namespaced_deployment(body=client.V1Deployment(yaml_content),namespace="default")

    return "Deployment created"

@app.route('/deploy', methods=['POST'])
def deploy_handler():
    yaml_file = request.get_json()
    yaml_file = yaml_file["yaml_file"]
    if not os.path.isfile(yaml_file):
        return f"YAML file '{yaml_file}' does not exist"
    else:
        deploy_yaml(yaml_file)

if __name__ == '__main__':
    main()
    app.run(host='0.0.0.0', port=8080)
```

**here is what happen:**

```
[2023-06-08 07:47:54,800] ERROR in app: Exception on /deploy [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8890780fd0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/cloneyaml/applyv2.py", line 35, in deploy_handler
    deploy_yaml(yaml_file)
  File "/cloneyaml/applyv2.py", line 23, in deploy_yaml
    api_instance.create_namespaced_deployment(body=client.V1Deployment(yaml_content),namespace="default")
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/apps_v1_api.py", line 353, in create_namespaced_deployment
    return self.create_namespaced_deployment_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/apps_v1_api.py", line 452, in create_namespaced_deployment_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 275, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 168, in request
    r = self.pool_manager.request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/apps/v1/namespaces/default/deployments (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8890780fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
10.244.0.1 - - [08/Jun/2023 07:47:54] "POST /deploy HTTP/1.1" 500 -
```

**What I expected to happen:**
I want to use my yaml that in my pod to create deployment.

**How to reproduce it (as minimally and precisely as possible):**
```
python3 applyv2.py # inside pod
curl -X POST -H "Content-Type: application/json" -d '{"yaml_file":"999.yaml"}' http://10.244.0.137:8080/deploy # out of pod
```

Enviroment:
```
Kubernetes:1.23
OS:ubuntu 20.04
Python:3.9
Kubernetes-client-python:23.3.0
```

Is there have any solution ?

**Comment by fabianvf** [comment]
@fword-newbie I think the issue is that you're creating the api client before the incluster config is loaded. If you create the api client after you load included config this should work
