### ISSUE TITLE
Use kubectl top node with the package

### ISSUE THREAD

**Issue by maximematheron** [kubernetes-client/python#435]
Hi everybody,

the command `kubectl top node` is really powerful but i cannot find the equivalent in the python package documentation. Before implementing my own, I would like to check with the community if there is an alternative in the package.

Maxime

**Comment by maximematheron** [comment]
Ok,

**Comment by g-jgreen** [comment]
@maximematheron 
Did you find it in the end?

**Comment by abushoeb** [comment]
Any update on this? I'm looking for it too.

**Comment by strimpak** [comment]
I'm looking for it too.

**Comment by y-spreen** [comment]
For all pods:

```
from kubernetes import client

api = client.CustomObjectsApi()
api.list_cluster_custom_object("metrics.k8s.io", "v1beta1", "pods")
```

for a single pod

```
from kubernetes import client

api = client.CustomObjectsApi()
api.get_namespaced_custom_object("metrics.k8s.io", "v1beta1", "default", "pods", "99532ba6-33ac-450b-ad49-285cfccf53c1-swqsh")
```

@g-jgreen @abushoeb @strimpak

**Comment by y-spreen** [comment]
Should work for nodes the same.

**Comment by ChocolatePadmanaban** [comment]
@yspreen 
i tied to replicate you your method but i got stuck with this error
`>>> from kubernetes import client, config
>>> config.load_kube_config()
>>> api = client.CustomObjectsApi()
>>> 
>>> 
>>> resource = api.get_namespaced_custom_object(group="metrics.k8s.io",version="v1", name="addon-catalog-source-wtbtz", namespace="ibm-system" , plural="pods")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 954, in get_namespaced_custom_object
    (data) = self.get_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, **kwargs)  # noqa: E501
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 1043, in get_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 362, in request
    return self.rest_client.GET(url,
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/rest.py", line 237, in GET
    return self.request("GET", url,
  File "/home/pradeepp/miniconda3/envs/workout/lib/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 17 Sep 2020 06:07:03 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
`

**Comment by vincent-haoy** [comment]
Is there any way to get the cpu&memory usage in percentage? Thx.
