### ISSUE TITLE
Authentication issues on GCE

### ISSUE THREAD

**Issue by jobevers** [kubernetes-client/python#448]
kubernetes authorization fails when I try using the python api first:
```
$ rm ~/.kube/config
$ gcloud container clusters get-credentials <cluster>
Fetching cluster endpoint and auth data.
kubeconfig entry generated for <cluster>.
$ python example1.py
[...]
HTTP response body: Unauthorized
$ kubectl get pods
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

But works when I run the `kubectl` client first:
```
$ rm ~/.kube/config
$ gcloud container clusters get-credentials <cluster>
Fetching cluster endpoint and auth data.
kubeconfig entry generated for <cluster>.
$ kubectl get pods
NAME                                      READY     STATUS    RESTARTS   AGE
[...]
$ python example1.py
Listing pods with their IPs:
[...]
```

**Comment by jobevers** [comment]
Version:
```
$ gcloud -v
Google Cloud SDK 186.0.0
alpha 2017.09.15
beta 2017.09.15
bq 2.0.28
core 2018.01.22
gsutil 4.28
kubectl
```

**Comment by AbhinavanT** [comment]
What is the status on this issue? It is extremely inconvenient dealing with this issue as I am trying to run a python app in a container to manager deployments and I haven't found a way to get it to work. Even adding `kubectl get pods` before `python my_script.py` in the start-up script run under docker-compose.yml doesn't work. I am only able to get the script to run by going into the container and executing.

**Comment by cbrinley219** [comment]
I have a very similar issue which I am pretty sure is a RBAC config issue but I'd appreciate any guidance that can be given. 

from the basic example on the project home page:
```
v1.list_node()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13214, in list_node
    (data) = self.list_node_with_http_info(**kwargs)
  File "/Library/Python/2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13311, in list_node_with_http_info
    collection_formats=collection_formats)
  File "/Library/Python/2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/Library/Python/2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/Library/Python/2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/Library/Python/2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/Library/Python/2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 11 May 2018 15:39:20 GMT', 'Content-Length': '129', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

However i am a cluster admin and all commands work with `kubectl` 
Does anyone have any experience that might help me fix up permissions for this kind of API access

Thanks

**Comment by jobevers** [comment]
I've migrated to using `subprocess.run(['kubectl', ...])`, so I'll just let this stay stale.

**Comment by jbresciani** [comment]
I'm seeing the same issue, I'd rather not hack it with a kubectl subprocess but I will if that's the official solution

**Comment by jbresciani** [comment]
I should have tried this first, but I fixed my issue by setting the env var GOOGLE_APPLICATION_CREDENTIALS with the file path of the JSON file that contains your service account key. Now it works as expected.
