### ISSUE TITLE
Unable to connect to k8s cluster

### ISSUE THREAD

**Issue by Formartha** [kubernetes-client/python#468]
Hi,

I'm trying to use the client to instantiate a simple connection. however, I fail on the following errors:

/usr/bin/python2.7 /root/PycharmProjects/new/playground/mor/k8s_interface.py
Listing pods with their IPs:
/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
2018-02-28 09:01:05,211 ERROR Certificate did not match expected hostname: 10.247.252.151. Certificate: {'notAfter': 'Feb 22 10:28:48 2019 GMT', 'subjectAltName': ((u'DNS', 'kubernetes-master-nft1-8803-02-22-18'), (u'DNS', 'kubernetes'), (u'DNS', 'kubernetes.default'), (u'DNS', 'kubernetes.default.svc'), (u'DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '10.96.0.1'), ('IP Address', '10.247.252.151')), 'subject': ((('commonName', u'kube-apiserver'),),)}
2018-02-28 09:01:05,211 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.247.252.151' doesn't match either of 'kubernetes-master-nft1-8803-02-22-18', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'",),)': /api/v1/pods?watch=False
/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
2018-02-28 09:01:05,223 ERROR Certificate did not match expected hostname: 10.247.252.151. Certificate: {'notAfter': 'Feb 22 10:28:48 2019 GMT', 'subjectAltName': ((u'DNS', 'kubernetes-master-nft1-8803-02-22-18'), (u'DNS', 'kubernetes'), (u'DNS', 'kubernetes.default'), (u'DNS', 'kubernetes.default.svc'), (u'DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '10.96.0.1'), ('IP Address', '10.247.252.151')), 'subject': ((('commonName', u'kube-apiserver'),),)}
2018-02-28 09:01:05,223 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.247.252.151' doesn't match either of 'kubernetes-master-nft1-8803-02-22-18', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'",),)': /api/v1/pods?watch=False
/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
2018-02-28 09:01:05,235 ERROR Certificate did not match expected hostname: 10.247.252.151. Certificate: {'notAfter': 'Feb 22 10:28:48 2019 GMT', 'subjectAltName': ((u'DNS', 'kubernetes-master-nft1-8803-02-22-18'), (u'DNS', 'kubernetes'), (u'DNS', 'kubernetes.default'), (u'DNS', 'kubernetes.default.svc'), (u'DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '10.96.0.1'), ('IP Address', '10.247.252.151')), 'subject': ((('commonName', u'kube-apiserver'),),)}
2018-02-28 09:01:05,235 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.247.252.151' doesn't match either of 'kubernetes-master-nft1-8803-02-22-18', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'",),)': /api/v1/pods?watch=False
/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
2018-02-28 09:01:05,248 ERROR Certificate did not match expected hostname: 10.247.252.151. Certificate: {'notAfter': 'Feb 22 10:28:48 2019 GMT', 'subjectAltName': ((u'DNS', 'kubernetes-master-nft1-8803-02-22-18'), (u'DNS', 'kubernetes'), (u'DNS', 'kubernetes.default'), (u'DNS', 'kubernetes.default.svc'), (u'DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '10.96.0.1'), ('IP Address', '10.247.252.151')), 'subject': ((('commonName', u'kube-apiserver'),),)}
Traceback (most recent call last):
  File "/root/PycharmProjects/new/playground/mor/k8s_interface.py", line 16, in <module>
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13589, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13686, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.247.252.151', port=6443): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by SSLError(CertificateError("hostname '10.247.252.151' doesn't match either of 'kubernetes-master-nft1-8803-02-22-18', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'",),))

Process finished with exit code 1

Can you please aid here?

**Comment by roycaihw** [comment]
Seems to be an SSLError, have you tried [`SSLError on macOS` and `Hostname doesn't match`](https://github.com/kubernetes-client/python/tree/3f4d09d260cf0839fae8173852c69e0419188454#sslerror-on-macos) in troubleshooting?

**Comment by Formartha** [comment]
I did.
None of them worked :(

Do you need any additional information to be able to assist me?

**Comment by roycaihw** [comment]
Just to be sure, could you copy the results from `python --version` and `pip freeze -r requirements.txt` here?

**Comment by Formartha** [comment]
sure!

**Python version output**
Python 2.7.5


**pip freeze output**
apipkg==1.4
appdirs==1.4.3
asn1crypto==0.24.0
astroid==1.6.1
attrs==17.4.0
Babel==1.3
backports.functools-lru-cache==1.5
backports.ssl-match-hostname==3.4.0.2
Beaker==1.5.4
blivet==0.18.34
Brlapi==0.6.0
cachetools==2.0.1
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
cliff==1.9.0
cmd2==0.6.8
configobj==4.7.2
configparser==3.5.0
configshell-fb==1.1.11
coverage==4.5.1
cryptography==2.1.4
cupshelpers==1.0
decorator==3.4.0
deprecation==1.2
di==0.3
dnspython==1.10.0
dogpile.cache==0.6.4
ecdsa==0.13
enum34==1.1.6
ethtool==0.8
execnet==1.5.0
firstboot==19.5
freeipa==2.0.0a0
fros==1.0
funcsigs==1.0.2
futures==3.2.0
google-auth==1.4.1
httplib2==0.9
idna==2.6
iniparse==0.4
initial-setup==0.3.9.12
ipaddr==2.1.9
ipaddress==1.0.19
ipapython==3.3.3
IPy==0.75
iso8601==0.1.12
isort==4.3.4
javapackages==1.0.0
jmespath==0.9.3
jsonpatch==1.21
jsonpointer==2.0
jsonschema==2.4.0
kerberos==1.1
keystoneauth1==3.4.0
kitchen==1.1.1
kmod==0.1
kubernetes==5.0.0
langtable==0.0.13
launchpadlib==1.6.0
lazr.authentication==0.1.3
lazr.restfulclient==0.13.1
lazr.uri==1.0.3
lazy-object-proxy==1.3.1
lxml==3.2.1
Mako==0.8.1
MarkupSafe==0.11
mccabe==0.6.1
msgpack-python==0.4.5
munch==2.2.0
netaddr==0.7.13
netifaces==0.10.4
oauth==1.0.1
oauthlib==2.0.6
openstacksdk==0.11.3
os-service-types==1.2.0
oslo.config==1.6.1
oslo.i18n==1.4.0
oslo.serialization==1.3.0
oslo.utils==1.3.0
packaging==16.8
paramiko==1.15.2
Paste==1.7.5.1
pathlib==1.0.1
pbr==3.1.1
pluggy==0.6.0
policycoreutils-default-encoding==0.1
prettytable==0.7.2
py==1.5.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pycrypto==2.6.1
pycups==1.9.63
pycurl==7.19.0
pygobject==3.8.2
pygpgme==0.3
pyinotify==0.9.4
pykickstart==1.99.43.10
pyliblzma==0.5.3
pylint==1.8.2
pyOpenSSL==17.5.0
pyparsing==2.0.3
pyparted==3.9
pytest==3.4.0
pytest-cov==2.5.1
pytest-forked==0.2
pytest-html==1.16.1
pytest-metadata==1.6.0
pytest-pylint==0.9.0
pytest-xdist==1.22.2
python-augeas==0.4.1
python-ceilometerclient==1.0.12
python-cinderclient==1.1.1
python-dateutil==2.6.1
python-default-encoding==0.1
python-glanceclient==0.15.0
python-heatclient==0.3.0
python-keystoneclient==1.1.0
python-ldap==2.4.6
python-meh==0.25
python-neutronclient==2.3.10
python-novaclient==2.20.0
python-nss==0.14.0
python-swiftclient==2.3.1
python-xlib==0.21
pytz==2014.10
pyudev==0.15
PyUserInput==0.1.11
pyxattr==0.5.1
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
requestsexceptions==1.4.0
rsa==3.4.2
rtslib-fb==2.1.46
selenium==3.9.0
seobject==0.1
sepolicy==1.1
setroubleshoot==1.1
simplejson==3.6.5
singledispatch==3.4.0.3
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
SSSDConfig==1.11.2
stevedore==1.28.0
targetcli-fb===2.1.fb34
Tempita==0.5.1
urlgrabber==3.10
urllib3==1.22
urwid==1.1.1
wadllib==1.3.2
warlock==1.1.0
websocket-client==0.47.0
wrapt==1.10.11
wsgi-intercept==0.9.1
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4
zope.interface==4.1.2

**Comment by roycaihw** [comment]
What is your openssl version from `python -c "import ssl; print ssl.OPENSSL_VERSION"`?

**Comment by Formartha** [comment]
@roycaihw  - OpenSSL 1.0.1e-fips 11 Feb 2013
