### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by lululalalulu03** [kubernetes-client/python#480]
run a dockerfile，content is：

> FROM jupyterhub/k8s-hub:v0.6
RUN pip3 install --upgrade --no-deps --force-reinstall kubernetes==4.0
ADD test.py ./
CMD ["python3", "test.py"]

test.py content is：

> from kubernetes import client, config
config.load_incluster_config()
v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))

but，connect to kubernetes api though python client，error is following：

> WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),)': /api/v1/namespaces/jup/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
2018-03-12 08:57:46,488 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),)': /api/v1/namespaces/jup/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),)': /api/v1/namespaces/jup/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server
[E 2018-03-12 08:57:46.493 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.6/types.py", line 184, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1382, in initialize
        yield self.init_spawners()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1210, in init_spawners
        self.users[orm_user.id] = user = User(orm_user, self.tornado_settings)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 178, in __init__
        self.spawners[name] = self._new_spawner(name)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 208, in _new_spawner
        spawner = spawner_class(**spawn_kwargs)

kubernetes version is 1.8.4，client version is 3.0 or 4.0

**Comment by aogier** [comment]
Hi, your example works out of the box for me on kubernetes 1.9 using minikube, anyway for letting client code works even with invalid ssl certs you could try to adapt [this solution](https://github.com/karmab/samplecontroller/pull/2/files). Basically, you have to instantiate a configuration object so it's underlying urllib3 calls ignore invalid certs.

Hope this helps, ciao !
