### ISSUE TITLE
Failed to run examples/exec.py on GKE

### ISSUE THREAD

**Issue by yujunz** [kubernetes-client/python#485]
I got an 400 error when running the exec example.

```
(clover-9mvhDOoI) ➜  clover python exec.py
Traceback (most recent call last):
  File "exec.py", line 64, in <module>
    stdout=True, tty=False)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 32, in stream
    return func(*args, **kwargs)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 835, in connect_get_namespaced_pod_exec
    (data) = self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 935, in connect_get_namespaced_pod_exec_with_http_info
    collection_formats=collection_formats)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 27, in _intercept_request_call
    return ws_client.websocket_call(config, *args, **kwargs)
  File "/home/yujunz/.virtualenvs/clover-9mvhDOoI/lib/python2.7/site-packages/kubernetes/stream/ws_client.py", line 255, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: Handshake status 400 Bad Request
```

Equivalent `kubectl` command works well

```
(clover-9mvhDOoI) ➜  clover kubectl exec busybox-test -- /bin/sh -c 'echo This message goes to stderr >&2; echo This message goes to stdout'
Defaulting container name to sleep.
Use 'kubectl describe pod/busybox-test' to see all of the containers in this pod.
This message goes to stdout
This message goes to stderr
```

Package versions for information

```
(clover-9mvhDOoI) ➜  clover pipenv graph
kubernetes==5.0.0
  - certifi [required: >=14.05.14, installed: 2018.1.18]
  - google-auth [required: >=1.0.1, installed: 1.4.1]
    - cachetools [required: >=2.0.0, installed: 2.0.1]
    - pyasn1-modules [required: >=0.2.1, installed: 0.2.1]
      - pyasn1 [required: <0.5.0,>=0.4.1, installed: 0.4.2]
    - rsa [required: >=3.1.4, installed: 3.4.2]
      - pyasn1 [required: >=0.1.3, installed: 0.4.2]
    - six [required: >=1.9.0, installed: 1.11.0]
  - ipaddress [required: >=1.0.17, installed: 1.0.19]
  - python-dateutil [required: >=2.5.3, installed: 2.7.0]
    - six [required: >=1.5, installed: 1.11.0]
  - pyyaml [required: >=3.12, installed: 3.12]
  - requests [required: Any, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.1.18]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - requests-oauthlib [required: Any, installed: 0.8.0]
    - oauthlib [required: >=0.6.2, installed: 2.0.6]
    - requests [required: >=2.0.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2018.1.18]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - setuptools [required: >=21.0.0, installed: 38.5.2]
  - six [required: >=1.9.0, installed: 1.11.0]
  - urllib3 [required: !=1.21,>=1.19.1, installed: 1.22]
  - websocket-client [required: >=0.32.0,!=0.41.*,!=0.40.0,!=0.42.*, installed: 0.47.0]
    - six [required: Any, installed: 1.11.0]
```

**Comment by illagrenan** [comment]
I have the same problem with Kubernetes on AWS. I've tried many combinations of `connect_get_namespaced_pod_exec` parameters and these are working for me:

```python
from pprint import pprint

from kubernetes.client import CoreV1Api
from kubernetes.stream import stream

exec_command = [
    '/bin/sh',
    '-c',
    'echo This message goes to stdout; ls / -alh'
]

api = CoreV1Api()
api_response = stream(api.connect_get_namespaced_pod_exec,
                      'pod-foo-bar',
                      'namespace-foo',
                      container='bar-container',
                      command=exec_command,
                      stderr=True,
                      stdin=False,
                      stdout=True,
                      tty=False,
                      _preload_content=True)

pprint(api_response)
```

**Comment by eightlimbed** [comment]
Thanks @illagrenan -- That combo is working for me, too (after trying a bunch of other stuff)

**Comment by Dorsivan** [comment]
Works great, thank you very much
