### ISSUE TITLE
SSLError excessive message size

### ISSUE THREAD

**Issue by hernandanielg** [kubernetes-client/python#531]
I am facing an issue with the client related to SSL, my situation is the following:

NOTE: My configuration works with `kubectl` we are trying to develop some tool with this k8s python client.

When I try to connect to my k8s cluster I get the following error
```
➜  ~  bpython
bpython version 0.17.1 on top of Python 2.7.13 /usr/bin/python 
>>> from kubernetes import client, config
>>> config.load_kube_config()
>>> v1 = client.CoreV1Api()
>>> 
>>> 
>>> v1.list_pod_for_all_namespaces(watch=False)
2018-05-11 10:17:54,512 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'read_state_machine', 'excessive message size')],)",),)': /api/v1/pods?watch=False
...

```

Tried to disable ssl verification and didn't work, same error
```
>>> configuration = client.Configuration()
>>> configuration.verify_ssl = False
```

My OpenSSL version
```
➜  ~  python -c "import ssl; print ssl.OPENSSL_VERSION"       
OpenSSL 1.1.0f  25 May 2017
```

I checked the certificates (self signed) and everything seems fine
```
➜  ~  bpython                                                                 
bpython version 0.17.1 on top of Python 2.7.13 /usr/bin/python
>>> from kubernetes import client, config
>>> config.load_kube_config()
>>> v1 = client.CoreV1Api()
>>> configuration = client.Configuration()
>>> configuration.cert_file
'/tmp/tmp0jL3yr'
>>> configuration.ssl_ca_cert
'/tmp/tmpZX2sEK'
>>>

➜  ~  openssl verify -CAfile /tmp/tmpZX2sEK /tmp/tmp0jL3yr                    
/tmp/tmp0jL3yr: OK
```

Then I noted that Public Key length is different from cert and CA cert, but not sure if this is related
```
➜  ~  openssl x509 -noout -text -in /tmp/tmpZX2sEK | grep Public-Key                                                                                           
                Public-Key: (2048 bit)
➜  ~  openssl x509 -noout -text -in /tmp/tmp0jL3yr | grep Public-Key
                Public-Key: (4096 bit)
```

Tried to activate debug mode and got this Traceback
```
>>> config.debug = True
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    v1.list_pod_for_all_namespaces(watch=False)           
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13608, in list_pod_for_all_namespaces  
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13705, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api     
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)    
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api   
    _request_timeout=_request_timeout)    
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request      
    headers=headers)  
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET    
    query_params=query_params)    
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)  
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/request.py", line 66, in request        
    **urlopen_kw)     
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/request.py", line 87, in request_encode_url         
    return self.urlopen(method, url, **extra_kw)          
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen   
    response = conn.urlopen(method, u.request_uri, **kw)  
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)    
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)    
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/hernandanielg/.local/lib/python2.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='some.k8scluster', port=6443): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'read_state_machine', 'excessive message size')],)",),))
```

Can somebody enlight me on how can I solve this? 

Thanks in advance

**Comment by eugene-dounar** [comment]
We've narrowed down this problem to the large size of our certificates. The client certs in kubeconfig contain many "O=" attributes. The x509 pem file is 43Kb and it crashes urllib3

**Comment by hernandanielg** [comment]
Thanks @eugene-dounar so it seems this issue should be addressed to https://github.com/urllib3/urllib3

Closing this issue :+1:
