### ISSUE TITLE
list_cluster_role_binding() and list_cluster_role_binding_with_http_info() failed with "Invalid value for `subjects`, must not be `None`"

### ISSUE THREAD

**Issue by g3rzi** [kubernetes-client/python#577]
The function `list_cluster_role_binding()` failed with the following errors:
```
Traceback (most recent call last):
  File "/home/myuser/Desktop/pycharm-community-2018.1.4/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/apis/rbac_authorization_v1_api.py", line 1695, in list_cluster_role_binding
    (data) = self.list_cluster_role_binding_with_http_info(**kwargs)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/apis/rbac_authorization_v1_api.py", line 1792, in list_cluster_role_binding_with_http_info
    collection_formats=collection_formats)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 254, in __deserialize
    for sub_data in data]
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 254, in <listcomp>
    for sub_data in data]
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/models/v1_cluster_role_binding.py", line 68, in __init__
    self.subjects = subjects
  File "/root/PycharmProjects/KubeProject/venv/lib/python3.5/site-packages/kubernetes/client/models/v1_cluster_role_binding.py", line 185, in subjects
    raise ValueError("Invalid value for `subjects`, must not be `None`")
ValueError: Invalid value for `subjects`, must not be `None`

```

**How to reproduce:**  
Run the following code from python:  
```
from kubernetes import client
v1 = client.RbacAuthorizationV1Api()
v1.list_cluster_role_binding()
```

Same errors happen with `list_cluster_role_binding_with_http_info()`.

My Kubernetes master (Minikube) is working and I can get the clusterroles with `kuebctl get clusterroles`

**Comment by roycaihw** [comment]
Dup of https://github.com/kubernetes-client/python/issues/513. Please see https://github.com/kubernetes-client/gen/issues/52
