### ISSUE TITLE
getting error OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

### ISSUE THREAD

**Issue by shenyanping** [kubernetes-client/python#620]
test.py:
from kubernetes import client, config, watch

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config(config_file="kubeconfig.yaml")
v1 = client.CoreV1Api()
print("Listing All services with their info:\n")
ret = v1.list_service_for_all_namespaces(watch=False)
for i in ret.items:
    print(
        "%s \t%s \t%s \t%s \t%s \n" % (i.kind, i.metadata.namespace, i.metadata.name, i.spec.cluster_ip, i.spec.ports))

but get error：
2018-09-11 12:41:44,635 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/services?watch=False
2018-09-11 12:41:44,715 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/services?watch=False
2018-09-11 12:41:44,794 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/services?watch=False
Traceback (most recent call last):
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/syp/Desktop/test/k8s/test3.py", line 7, in <module>
    ret = v1.list_service_for_all_namespaces(watch=False, _request_timeout=100000)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 14358, in list_service_for_all_namespaces
    (data) = self.list_service_for_all_namespaces_with_http_info(**kwargs)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 14455, in list_service_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/syp/Desktop/test/k8s/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c91925975597746a2adf5918c57b7707c.serverless-1.kubernetes.cn-shanghai.aliyuncs.com', port=6443): Max retries exceeded with url: /api/v1/services?watch=False (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by opszhy** [comment]
这个问题请问您解决了吗？

**Comment by karthi81** [comment]
I'm also getting the same Error.

Python 3.6.7
requests 2.20.1

**Comment by GeekSRE** [comment]
`# -*- coding: utf-8 -*-
from django.db import models
from kubernetes import client, config
import urllib3

urllib3.disable_warnings()

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

# Create a configuration object
aConfiguration = client.Configuration()
aConfiguration.verify_ssl = False     #关键点

api_client = client.ApiClient(aConfiguration)`


配置上  aConfiguration.verify_ssl = False     这个就ok了

**Comment by scottilee** [comment]
@shenyanping I was able to run your example and get all services running in my cluster. Are you able to run `kubectl get svc --all-namespaces` without issue?

```
from kubernetes import client, config, watch

config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing All services with their info:\n")
ret = v1.list_service_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s \t%s \t%s \t%s \t%s \n" % (i.kind, i.metadata.namespace, i.metadata.name, i.spec.cluster_ip, i.spec.ports))
```
