### ISSUE TITLE
kubernetes client fails within python flask

### ISSUE THREAD

**Issue by supcom234** [kubernetes-client/python#643]
Calling any kubernetes call within a flask context seems to fail with recursion errors.

**Versions:**
Flask-Cors==3.0.6
Flask-SocketIO==3.0.1
Flask==1.0.2
kubernetes==7.0.0

**Traceback (most recent call last):**
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/tfplenum-frontend/backend/app/configmap_controller.py", line 33, in save_config_map
    kube_apiv1.list_config_map_for_all_namespaces_with_http_info()
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11121, in list_config_map_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/opt/tfplenum-frontend/tfp-env/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 293, in create_urllib3_context
    context.options |= options
  File "/usr/lib64/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
... etc etc
  File "/usr/lib64/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib64/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib64/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib64/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
RecursionError: maximum recursion depth exceeded

**Comment by supcom234** [comment]
Never mind this error was my own stupidity.  I for got to monkey patch my server with.

import gevent.monkey
gevent.monkey.patch_all()

from requests.packages.urllib3.util.ssl_ import create_urllib3_context
create_urllib3_context()

**Comment by roycaihw** [comment]
@supcom234 Thanks for explaining :) Closing
