### ISSUE TITLE
Resource creation function call fails with type object 'datetime.datetime' has no attribute 'swagger_types'

### ISSUE THREAD

**Issue by Eronarn** [kubernetes-client/python#646]
Tested with `kubernetes==8.0.0a1` (`kubernetes==7.0.0` has a bug that prevents exec-based auth from working properly so could not test it there on my setup). Here is a stack trace, plus the body of the ConfigMap API response:

```
models.py                 1569 INFO     Executing <Task(JobTemplateOperator): helm_template> on 2018-07-10 00:00:00+00:00
rest.py                    219 DEBUG    response body: {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"airflow-testing-local.test-helm-template.helm-template-job-test","namespace":"staging","selfLink":"/api/v1/namespaces/staging/configmaps/airflow-testing-local.test-helm-template.helm-template-job-test","uid":"e3249627-ce27-11e8-938f-123df6ebd098","resourceVersion":"76747424","creationTimestamp":"2018-10-12T14:05:34Z","labels":{}},"data":{"reason":"workaround for helm no objects visited"}}

models.py                 1736 ERROR    type object 'datetime.datetime' has no attribute 'swagger_types'
Traceback (most recent call last):
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/airflow/models.py", line 1633, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/eronarn/Code/quantflow/quantflow/operators/helm_operators.py", line 443, in execute
    namespace=self.namespace)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 5522, in create_namespaced_config_map
    (data) = self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 5607, in create_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/eronarn/Code/quantflow/.tox/py35/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 610, in __deserialize_model
    if not klass.swagger_types and not hasattr(klass, 'get_real_child_model'):
AttributeError: type object 'datetime.datetime' has no attribute 'swagger_types'
```

The observed behavior is that the ConfigMap is created, but the function raises an exception before it returns.

**Comment by Eronarn** [comment]
This is also happening with Jobs for me so I changed the title. Again, it creates the resource fine, and something about the return value getting coerced into an object is raising this exception.
