### ISSUE TITLE
urllib3.exceptions.ReadTimeoutError when using kubernetes.watch.Watch()

### ISSUE THREAD

**Issue by zerthimon** [kubernetes-client/python#686]
I'm doing a loop that watches namespaces constantly:
```
for event in watch.stream(CoreV1Api.list_namespace, _request_timeout=180):
```
and getting
```
Traceback (most recent call last):
  File "na.py", line 17, in <module>
    for event in watch.stream(CoreV1Api.list_namespace, _request_timeout=180):
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/watch/watch.py", line 130, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/watch/watch.py", line 45, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='172.30.1.30', port=6443): Read timed out.
```

Is there a way to avoid these timeouts or should I catch this exception and restart the loop each time it happens ?

**Comment by micw523** [comment]
Um... I thought the request_timeout is an optional parameter?

Am I missing something?

**Comment by prasad1991** [comment]
Hi have also facing same issue but my pods are automatically deleted
