### ISSUE TITLE
list_pod_security_policy returning 404 error (PolicyV1betaApi)

### ISSUE THREAD

**Issue by nlynch71** [kubernetes-client/python#702]
Hi,
As described in the title, i'm currently experiencing a problem where `list_pod_security_policy` in the PolicyV1betaApi is returning a 404 not found error. The cluster I am testing on is a google kubernetes engine version 1.9.7-gke.11 cluster.

The full error is:
`Traceback (most recent call last):
  File "main.py", line 168, in <module>
    generatepsptabcontent()
  File "main.py", line 129, in generatepsptabcontent
    ret = pol.list_pod_security_policy(include_uninitialized=True)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/apis/policy_v1beta1_api.py", line 1142, in list_pod_security_policy
    (data) = self.list_pod_security_policy_with_http_info(**kwargs)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/apis/policy_v1beta1_api.py", line 1239, in list_pod_security_policy_with_http_info
    collection_formats=collection_formats)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/home/dev/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ac76a410-9532-4542-b1c9-402fd56b0f47', 'Content-Type': 'application/json', 'Date': 'Tue, 11 Dec 2018 16:50:11 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}`

There are no pod security policies present on the cluster however I was expecting the API call to return something empty like: 
`{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}`
Which is returned by the command `kubectl get psp`
Any insight into this issue would be much appreciated.
Cheers

**Comment by micw523** [comment]
If I'm not mistaken, you'll probably see this behavior across all languages.
