### ISSUE TITLE
Refresh token/api-key periodically

### ISSUE THREAD

**Issue by aparamon** [kubernetes-client/python#741]
Currently, authorization token/api-key is only initialized on loading config:
https://github.com/kubernetes-client/python-base/blob/bd9a8525e9215f7f01c32a321beb9a605cf0402b/config/kube_config.py#L420
https://github.com/kubernetes-client/python-base/blob/bd9a8525e9215f7f01c32a321beb9a605cf0402b/config/kube_config.py#L510
When working with Amazon EKS via [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) though, token/api-key expires relatively quickly.

It is proposed to introduce a configurable option to specify token/api-key time-to-live. On API call the time should be checked, and if expired the token/api-key should be refreshed by calling https://github.com/kubernetes-client/python-base/blob/bd9a8525e9215f7f01c32a321beb9a605cf0402b/config/kube_config.py#L350 again.
Alternatively, API client could check for `401 Unauthorized` return code and refresh token (at most once per API call).

**Comment by marsewe** [comment]
See also https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/63 and https://stackoverflow.com/questions/48151388/kubernetes-python-client-authentication-issue .

**Comment by Eronarn** [comment]
Calling `config.load_kube_config()` again doesn't seem to recreate a token in my case, even though the corresponding kubectl command would have automatically done so. So I think there's some staleness check here that isn't actually occurring.

**Comment by houqp** [comment]
config for an existing client is cached unfortunately :( After calling `load_kube_config`, you will have to recreate a new api client to pick up the refreshed token. Currently, the `expirationTimestamp` returned from `aws-iam-authenticator` is ignored by `KubeConfigLoader`.

**Comment by wing328** [comment]
@houqp I wonder if you can send the patch upstream to [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) as that's what the project going to use moving forward to generate API clients: https://github.com/kubernetes-client/gen/issues/93

**Comment by houqp** [comment]
Good call @wing328, do you know if https://github.com/kubernetes-client/python/pull/738 and https://github.com/kubernetes-client/gen/pull/97 are the right PRs to watch?

**Comment by houqp** [comment]
@wing328 i have ported the patches to openapi-generator, could you help review them?

**Comment by roycaihw** [comment]
kubernetes-client/gen#97 is merged. We used openapi-generator in 11.0.0a1 release https://github.com/kubernetes-client/python/pull/931

**Comment by jdamata** [comment]
I'm using 11.0.0a1 but still getting intermittent 401's 

```
{"asctime": "2019-11-13 14:38:33,384", "name": "k8s", "levelname": "INFO", "message": "Sleeping for 60 seconds"}
Traceback (most recent call last):
  File "src/main.py", line 57, in <module>
    drain.run()
  File "/opt/git/stratus/stratus-eks/worker_node_rolling_update/src/k8s.py", line 42, in run
    self.drain()
  File "/opt/git/stratus/stratus-eks/worker_node_rolling_update/src/k8s.py", line 33, in drain
    if check_node_drained(self.v1api, node):
  File "/opt/git/stratus/stratus-eks/worker_node_rolling_update/src/k8s_helper.py", line 117, in check_node_drained
    node_body = api.read_node(node_name)
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 20565, in read_node
    (data) = self.read_node_with_http_info(name, **kwargs)  # noqa: E501
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 20649, in read_node_with_http_info
    collection_formats=collection_formats)
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 166, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 356, in request
    headers=headers)
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/rest.py", line 241, in GET
    query_params=query_params)
  File "/Users/damatj/.local/share/virtualenvs/worker_node_rolling_update-n2X_lDEC/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '96bc2da9-40a0-42b8-9303-3a99b5d77db1', 'Content-Type': 'application/json', 'Date': 'Wed, 13 Nov 2019 19:39:33 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

**Comment by athom** [comment]
` 11.0.0b2` also not work

```
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/airflow/contrib/kubernetes/pod_launcher.py", line 168, in read_pod
     return self._client.read_namespaced_pod(pod.name, pod.namespace)
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 19078, in read_namespaced_pod
     (data) = self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 19169, in read_namespaced_pod_with_http_info
     collection_formats=collection_formats)
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 335, in call_api
     _preload_content, _request_timeout)
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 166, in __call_api
     _request_timeout=_request_timeout)
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 356, in request
     headers=headers)
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/rest.py", line 241, in GET
     query_params=query_params)
   File "/etc/airflow/.local/share/virtualenvs/airflow-bTdwlyD1/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request
     raise ApiException(http_resp=r)
 kubernetes.client.rest.ApiException: (401)
 Reason: Unauthorized
 HTTP response headers: HTTPHeaderDict({'Audit-Id': '685e7f66-8303-418c-9d1d-b82920ef2d0f', 'Content-Type': 'application/json', 'Date': 'Wed, 11 Dec 2019 04:12:24 GMT', 'Content-Length': '129'})
 HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

```

**Comment by roycaihw** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/3594 was included in openapi-generator 4.1.1. Currently we are still using openapi-generator [3.3.4](https://github.com/kubernetes-client/gen/blob/e056721a80bf2198c505998052b2814168450a96/openapi/openapi-generator/client-generator.sh#L44). We are tracking upgrading openapi-generator in the next major release: https://github.com/kubernetes-client/python/issues/1052, https://github.com/kubernetes-client/python/pull/1088

**Comment by dinvlad** [comment]
/remove-lifecycle stale

Any updates on this issue please? We're still getting affected by it quite a bit.

**Comment by drobison00** [comment]
Is there any ongoing work to resolve this issue?

**Comment by dinvlad** [comment]
This issue has been affecting us quite a lot - @roycaihw could please assign someone to look further into it? We just need an approximate timeline on what it could be addressed, so we can plan ahead if we need to come up with a workaround in the near term or just to wait on the fix (and others, please chime in if you have a workaround already!)

**Comment by houqp** [comment]
@dinvlad i have pushed my workaround into Airflow at https://github.com/apache/airflow/blob/master/airflow/kubernetes/kube_client.py. We have been running Airflow with this custom client in production for more than a year now without any issue.

**Comment by Uznick** [comment]
We have a similiar workaround as well. Works fine for now.

**Comment by dinvlad** [comment]
@houqp by looking at your [code](https://github.com/apache/airflow/blob/1cdd1cd3a356e95975357da2dc65ff2afb2a63c7/airflow/kubernetes/kube_client.py#L40), it uses the default `load_incluster_config()` when running inside the cluster. Does it mean you only experience this issue with the default `load_kube_config()`? We're seeing it even with `load_incluster_config()`, if I'm reading that right.

**Comment by dinvlad** [comment]
To more specifically expand on our issue (which might be slightly different from others' use of config loader here), we use `load_incluster_config()` for in-cluster cleanup operation, which in our case is the following pseudo-code:
```py3
from kubernetes.watch import Watch

def cleanup(namespace: str):
    """
    Watches for and deletes terminated Jobs.
    This function would not normally be needed if `ttlSecondsAfterFinished` worked.
    However, that feature is currently hidden behind an `alpha` flag in GKE.
    """
    load_incluster_config()
    api = BatchV1Api()
    events = Watch().stream(api.list_namespaced_job, namespace)
    for event in events:
        # cleanup logic
```
So our issue (if I'm not mistaken) is that no matter how credentials are fetched (either in-cluster or not), they seem to be "cached" in the config, and then `stream()` generator expires. I wonder if there's a more general way to implement a config client that refreshes credentials automatically.

Please correct me if that's what's already happening in `load_incluster_config()`, and our issue (watcher stops working after a while) is caused by something else (like the keepalive problem etc.)

**Comment by houqp** [comment]
@dinvlad my fix was only for out of cluster communication where auth goes through iam-authenticator. IIRC, in cluster communication uses builtin K8S auth, which doesn't have this problem.

**Comment by alexcristi** [comment]
Hi there! Any updates on this?

**Comment by kwlzn** [comment]
is anyone actively working on this issue? if not, my team at Twitter might try to take a stab at it soon.
