### ISSUE TITLE
ValueError on `pip install kubernetes` on Debian 8

### ISSUE THREAD

**Issue by jfrederickson** [kubernetes-client/python#769]
Attempting to install the Kubernetes Python client library on a system running Debian 8; I got this error during the installation:

```
root@localhost:~/db_netrulesgen# pip install kubernetes
Downloading/unpacking kubernetes
  Downloading kubernetes-8.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 49, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'websocket-client !=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0', 'at', '*,!=0.42.*,>=0.32.0')

Storing debug log for failure in /root/.pip/pip.log
```
Python version: 2.7.9
pip version: 1.5.6

On the same system, with `tags/v8.0.1` checked out, I get this when trying to install locally:
```
root@localhost:~/python# python setup.py install
error in kubernetes setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

**Comment by micw523** [comment]
It looks like the websocket-client requirement you have is different from what we have here. I wonder why...

**Comment by micw523** [comment]
On the repo, the “>=0.32.0” is shown as the first version requirement. On your system it is shown as the last requirement instead. https://github.com/kubernetes-client/python/blob/release-8.0/requirements.txt

**Comment by jfrederickson** [comment]
Looks like the version list in requirements.txt in the tarball[0] from PyPI matches what's in the repo. However, the `METADATA` file in the wheel[1] served from PyPI has them in a different order:

```
Requires-Dist: websocket-client (!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0)
```

I don't know enough about the Python build tooling or the build process for this package to say why that's the case at this point.

[0] https://files.pythonhosted.org/packages/14/77/9b2cf29fa6ec6b774e83e66acce08d75ecddaeaffdd922bcd78f2ff81e9c/kubernetes-8.0.1.tar.gz
[1] https://files.pythonhosted.org/packages/40/eb/4d6a80db84ac24c867c94fbf16e6f26db9780f5232f46ddd2e5539b42205/kubernetes-8.0.1-py2.py3-none-any.whl
