### ISSUE TITLE
SSL not available

### ISSUE THREAD

**Issue by Polaris0112** [kubernetes-client/python#777]
I want to run a python script to get stream from kubernetes api as below.

```python
#!/usr/bin/env python
#--coding:utf-8--

from kubernetes import client, config, watch
from kubernetes.stream import stream
config.load_kube_config()
k8s_corev1 = client.CoreV1Api()

def run_command_inside_pod(api_instance, pod, ns, exec_command):
    api_response = stream(api_instance.connect_get_namespaced_pod_exec, pod, ns,
                          command=exec_command,
                          stderr=True, stdin=False,
                          stdout=True, tty=False)
    return api_response


def metrics_datastore_check():
    """

    :param name:
    :return:
    """
    name = "mall-web-54f84b59b6-6f6jz"

    print("Waiting for pod %s to get ready." % name)
    exec_command = ['ls']
    es_status = run_command_inside_pod(k8s_corev1,name,"default",exec_command)
    print (es_status)

    print (type(es_status))

metrics_datastore_check()
```
but  it show that
```shell
# python k8s_exec.py
Waiting for pod mall-web-54f84b59b6-6f6jz to get ready.
https://172.16.18.175:8443/api/v1/namespaces/default/pods/mall-web-54f84b59b6-6f6jz/exec?command=ls&stderr=True&stdin=False&stdout=True&tty=False
Traceback (most recent call last):
  File "k8s_exec.py", line 32, in <module>
    metrics_datastore_check()
  File "k8s_exec.py", line 27, in metrics_datastore_check
    es_status = run_command_inside_pod(k8s_corev1,name,"default",exec_command)
  File "k8s_exec.py", line 13, in run_command_inside_pod
    stdout=True, tty=False)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 32, in stream
    return func(*args, **kwargs)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 835, in connect_get_namespaced_pod_exec
    (data) = self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 935, in connect_get_namespaced_pod_exec_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 27, in _intercept_request_call
    return ws_client.websocket_call(config, *args, **kwargs)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/stream/ws_client.py", line 257, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: SSL not available.
```

# python --version
Python 2.7.5

gevent-websocket==0.10.1
kubernetes==7.0.0
websocket-client==0.55.0

I also use these client file to run a python scripts to list all namespaces pod detail, and it work. 
So I think it is the websocket problem, do anyone know something about it ? I search many ways but doesn't work, hope to have some advises, many thanks.

**Comment by Polaris0112** [comment]
I search github all issue and change version of websocket-client package to 0.54.0 and it show other error detail 

```shell
Waiting for pod mall-web-54f84b59b6-6f6jz to get ready.
https://172.16.18.175:8443/api/v1/namespaces/default/pods/mall-web-54f84b59b6-6f6jz/exec?command=ls&stderr=True&stdin=False&stdout=True&tty=False
Traceback (most recent call last):
  File "k8s_exec.py", line 32, in <module>
    metrics_datastore_check()
  File "k8s_exec.py", line 27, in metrics_datastore_check
    es_status = run_command_inside_pod(k8s_corev1,name,"default",exec_command)
  File "k8s_exec.py", line 13, in run_command_inside_pod
    stdout=True, tty=False)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 32, in stream
    return func(*args, **kwargs)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 835, in connect_get_namespaced_pod_exec
    (data) = self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 935, in connect_get_namespaced_pod_exec_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 27, in _intercept_request_call
    return ws_client.websocket_call(config, *args, **kwargs)
  File "/usr/local/scripts/kubernetes-web-terminal/env/lib/python2.7/site-packages/kubernetes/stream/ws_client.py", line 257, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: Handshake status 404 Not Found
```

**Comment by jorgesece** [comment]
Hi @Polaris0112 did you solved it? I having the same issue and it would help me.

**Comment by LeoLiuYan** [comment]
+1
