### ISSUE TITLE
StorageClass objects returned by StorageV1Api.list_storage_class() ignore reclaimPolicy from API response

### ISSUE THREAD

**Issue by juliohm1978** [kubernetes-client/python#834]
Using kubernetes python client v9.0.0 to list storage classes in the cluster.

The following is a quick test case:

```
storageapi = kubernetes.client.StorageV1Api()
print("SC LIST BEGIN")
for item in storageapi.list_storage_class().items:
    print("===")
    print(item)
    print("===")
print("SC LIST END")
```

With logging DEBUG enabled, the output is as follows:

```
2019-05-18 23:15:04,693 [DEBUG] response body: {"kind":"StorageClassList","apiVersion":"storage.k8s.io/v1","metadata":{"selfLink":"/apis/storage.k8s.io/v1/storageclasses","resourceVersion":"312581"},"items":[{"metadata":{"name":"local-path","selfLink":"/apis/storage.k8s.io/v1/storageclasses/local-path","uid":"4a3b8f33-69fa-11e9-babd-641c678d3d92","resourceVersion":"51704","creationTimestamp":"2019-04-28T21:12:11Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"local-path\"},\"provisioner\":\"rancher.io/local-path\",\"reclaimPolicy\":\"Delete\",\"volumeBindingMode\":\"WaitForFirstConsumer\"}\n"}},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"},{"metadata":{"name":"sc01","selfLink":"/apis/storage.k8s.io/v1/storageclasses/sc01","uid":"4950b8cc-79a9-11e9-8f64-641c678d3d92","resourceVersion":"296853","creationTimestamp":"2019-05-18T20:12:39Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"sc01\"},\"mountOptions\":[\"debug\"],\"parameters\":{\"pvNamePrefix\":\"\",\"server\":\"10.10.10.3\",\"share\":\"meushare\"},\"provisioner\":\"juliohm.com.br/nfs-provisioner\",\"reclaimPolicy\":\"Retain\",\"volumeBindingMode\":\"Immediate\"}\n"}},"provisioner":"juliohm.com.br/nfs-provisioner","parameters":{"pvNamePrefix":"","server":"10.10.10.3","share":"meushare"},"reclaimPolicy":"Retain","mountOptions":["debug"],"volumeBindingMode":"Immediate"},{"metadata":{"name":"sc02","selfLink":"/apis/storage.k8s.io/v1/storageclasses/sc02","uid":"49510eea-79a9-11e9-8f64-641c678d3d92","resourceVersion":"296854","creationTimestamp":"2019-05-18T20:12:39Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"sc02\"},\"mountOptions\":[\"debug\"],\"parameters\":{\"type\":\"gp2\"},\"provisioner\":\"kubernetes.io/aws-ebs\",\"reclaimPolicy\":\"Retain\",\"volumeBindingMode\":\"Immediate\"}\n"}},"provisioner":"kubernetes.io/aws-ebs","parameters":{"type":"gp2"},"reclaimPolicy":"Retain","mountOptions":["debug"],"volumeBindingMode":"Immediate"}]}

===
{'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-path"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}\n'},
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2019, 4, 28, 21, 12, 11, tzinfo=tzutc()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'local-path',
              'namespace': None,
              'owner_references': None,
              'resource_version': '51704',
              'self_link': '/apis/storage.k8s.io/v1/storageclasses/local-path',
              'uid': '4a3b8f33-69fa-11e9-babd-641c678d3d92'},
 'parameters': None,
 'provisioner': 'rancher.io/local-path'}
===
===
{'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"sc01"},"mountOptions":["debug"],"parameters":{"pvNamePrefix":"","server":"10.10.10.3","share":"meushare"},"provisioner":"juliohm.com.br/nfs-provisioner","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}\n'},
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2019, 5, 18, 20, 12, 39, tzinfo=tzutc()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'sc01',
              'namespace': None,
              'owner_references': None,
              'resource_version': '296853',
              'self_link': '/apis/storage.k8s.io/v1/storageclasses/sc01',
              'uid': '4950b8cc-79a9-11e9-8f64-641c678d3d92'},
 'parameters': {'pvNamePrefix': '',
                'server': '10.10.10.3',
                'share': 'meushare'},
 'provisioner': 'juliohm.com.br/nfs-provisioner'}
===
===
{'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"sc02"},"mountOptions":["debug"],"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}\n'},
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2019, 5, 18, 20, 12, 39, tzinfo=tzutc()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'sc02',
              'namespace': None,
              'owner_references': None,
              'resource_version': '296854',
              'self_link': '/apis/storage.k8s.io/v1/storageclasses/sc02',
              'uid': '49510eea-79a9-11e9-8f64-641c678d3d92'},
 'parameters': {'type': 'gp2'},
 'provisioner': 'kubernetes.io/aws-ebs'}
===
```

While iterating through the list of storage classes, the field `reclaimPolicy` is not available in the object returned by the python library. The same field is present in the api response. It can be seen in the DEBUG message showing the full api json response before the library transforms that into a python object.

Looks like the kubernetes-client library is ignoring this field from the api response. Should we consider this a bug?

**Comment by tomplus** [comment]
Interesting, it works for me and I also have more fields

```
[cut]

 'mount_options': None,
 'parameters': {'type': 'Standard'},
 'reclaim_policy': 'Delete',
 'volume_binding_mode': 'Immediate'}

[cut]
```

could you check if this attribute is set by printing it directly:

```
storageapi = client.StorageV1Api()
res = storageapi.list_storage_class()
for item in res.items:
    print(item.reclaim_policy)
```

**Comment by juliohm1978** [comment]
Here's the simplest example I'm running.

```python
import kubernetes
import logging

logging.basicConfig(level=logging.DEBUG, format="%(asctime)s [%(levelname)s] %(message)s")

kubernetes.config.load_kube_config("/path/to/kube.config")
storageapi = kubernetes.client.StorageV1Api()
res = storageapi.list_storage_class()
for item in res.items:
    print(item.reclaim_policy)
```

This is the output.

```text
2019-05-22 08:42:58,525 [DEBUG] response body: {"kind":"StorageClassList","apiVersion":"storage.k8s.io/v1","metadata":{"selfLink":"/apis/storage.k8s.io/v1/storageclasses","resourceVersion":"391924"},"items":[{"metadata":{"name":"local-path","selfLink":"/apis/storage.k8s.io/v1/storageclasses/local-path","uid":"4a3b8f33-69fa-11e9-babd-641c678d3d92","resourceVersion":"51704","creationTimestamp":"2019-04-28T21:12:11Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"local-path\"},\"provisioner\":\"rancher.io/local-path\",\"reclaimPolicy\":\"Delete\",\"volumeBindingMode\":\"WaitForFirstConsumer\"}\n"}},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"},{"metadata":{"name":"sc01","selfLink":"/apis/storage.k8s.io/v1/storageclasses/sc01","uid":"4d5213da-7c43-11e9-8f64-641c678d3d92","resourceVersion":"383071","creationTimestamp":"2019-05-22T03:40:11Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"sc01\"},\"parameters\":{\"pvNamePrefix\":\"\",\"server\":\"192.168.100.58\",\"share\":\"/myshare\"},\"provisioner\":\"nfs-provisioner.juliohm.com.br\",\"reclaimPolicy\":\"Delete\",\"volumeBindingMode\":\"Immediate\"}\n"}},"provisioner":"nfs-provisioner.juliohm.com.br","parameters":{"pvNamePrefix":"","server":"192.168.100.58","share":"/myshare"},"reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}]}

Traceback (most recent call last):
  File "/home/lamento/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/lamento/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 410, in main
    run()
  File "/home/lamento/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lamento/Downloads/asdf.py", line 10, in <module>
    print(item.reclaim_policy)
AttributeError: 'V1StorageClass' object has no attribute 'reclaim_policy'
```

If I replace the print line:

```python
for item in res.items:
    print(item)
```

Here's the output:

```text
2019-05-22 08:44:32,693 [DEBUG] response body: {"kind":"StorageClassList","apiVersion":"storage.k8s.io/v1","metadata":{"selfLink":"/apis/storage.k8s.io/v1/storageclasses","resourceVersion":"391995"},"items":[{"metadata":{"name":"local-path","selfLink":"/apis/storage.k8s.io/v1/storageclasses/local-path","uid":"4a3b8f33-69fa-11e9-babd-641c678d3d92","resourceVersion":"51704","creationTimestamp":"2019-04-28T21:12:11Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"local-path\"},\"provisioner\":\"rancher.io/local-path\",\"reclaimPolicy\":\"Delete\",\"volumeBindingMode\":\"WaitForFirstConsumer\"}\n"}},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"},{"metadata":{"name":"sc01","selfLink":"/apis/storage.k8s.io/v1/storageclasses/sc01","uid":"4d5213da-7c43-11e9-8f64-641c678d3d92","resourceVersion":"383071","creationTimestamp":"2019-05-22T03:40:11Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"sc01\"},\"parameters\":{\"pvNamePrefix\":\"\",\"server\":\"192.168.100.58\",\"share\":\"/myshare\"},\"provisioner\":\"nfs-provisioner.juliohm.com.br\",\"reclaimPolicy\":\"Delete\",\"volumeBindingMode\":\"Immediate\"}\n"}},"provisioner":"nfs-provisioner.juliohm.com.br","parameters":{"pvNamePrefix":"","server":"192.168.100.58","share":"/myshare"},"reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}]}

{'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-path"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}\n'},
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2019, 4, 28, 21, 12, 11, tzinfo=tzutc()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'local-path',
              'namespace': None,
              'owner_references': None,
              'resource_version': '51704',
              'self_link': '/apis/storage.k8s.io/v1/storageclasses/local-path',
              'uid': '4a3b8f33-69fa-11e9-babd-641c678d3d92'},
 'parameters': None,
 'provisioner': 'rancher.io/local-path'}
{'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"sc01"},"parameters":{"pvNamePrefix":"","server":"192.168.100.58","share":"/myshare"},"provisioner":"nfs-provisioner.juliohm.com.br","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}\n'},
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2019, 5, 22, 3, 40, 11, tzinfo=tzutc()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'sc01',
              'namespace': None,
              'owner_references': None,
              'resource_version': '383071',
              'self_link': '/apis/storage.k8s.io/v1/storageclasses/sc01',
              'uid': '4d5213da-7c43-11e9-8f64-641c678d3d92'},
 'parameters': {'pvNamePrefix': '',
                'server': '192.168.100.58',
                'share': '/myshare'},
 'provisioner': 'nfs-provisioner.juliohm.com.br'}
```

I forgot to mention, my kubectl config is connecting to a [local k3s cluster](https://k3s.io/), which is a lightweight Kubernetes all-in-one binary.

But I'm not sure if this is really making any difference, since it's possible to see `"reclaimPolicy":"Delete"` in the log message showing the API server response body.

**Comment by juliohm1978** [comment]
I hit the "Close" button by accident. Sorry.

**Comment by tomplus** [comment]
> I hit the "Close" button by accident. Sorry.

Thankfully there is the reopen button too ;)

You get the error `AttributeError: 'V1StorageClass' object has no attribute 'reclaim_policy'`. But this attribute is defined here: https://github.com/kubernetes-client/python/blob/5e512ff564c244c50cab780d821542ed56aa965a/kubernetes/client/models/v1_storage_class.py#L283 as a `@property`. It looks like your python or installed libraries interfere with it or something?? Could you share you output from `pip freeze` and `python -v`. Thanks.

**Comment by juliohm1978** [comment]
Sure.

```text
> pip freeze and python -v
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Created temporary directory: /tmp/pip-ephem-wheel-cache-gwOi1_
ansible==2.7.10
asn1crypto==0.24.0
astroid==1.6.5
backports.functools-lru-cache==1.5
bcrypt==3.1.4
cachetools==3.1.0
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
Cheetah==2.4.4
Click==7.0
colorama==0.4.1
configobj==5.0.6
configparser==3.7.4
cryptography==2.6.1
dnspython==1.16.0
entrypoints==0.3
enum34==1.1.6
Flask==1.0.2
futures==3.2.0
google-auth==1.6.3
gyp==0.1
h5py==2.9.0
hvac==0.8.2
idna==2.8
ipaddr==2.2.0
ipaddress==1.0.22
isort==4.3.16
itsdangerous==1.1.0
Jinja2==2.10
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
keyring==18.0.1
kubernetes==9.0.0
lazy-object-proxy==1.3.1
libvirt-python==4.0.0
lxml==4.3.3
MarkupSafe==1.0
mccabe==0.6.1
netaddr==0.7.19
numpy==1.16.2
oauthlib==3.0.1
paramiko==2.4.1
pbr==5.1.3
Pillow==6.0.0
psutil==5.4.2
pyasn1==0.4.4
pyasn1-modules==0.2.5
pycairo==1.16.2
pycparser==2.18
pycrypto==2.6.1
pygobject==3.26.1
pylint==1.9.4
PyNaCl==1.2.1
pyparted==3.11.1
python-apt==1.6.4
python-dateutil==2.8.0
python-xlib==0.25
pyxdg==0.25
PyYAML==3.12
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
scipy==1.2.1
SecretStorage==2.3.1
setproctitle==1.1.10
singledispatch==3.4.0.3
six==1.12.0
urllib3==1.24.1
vboxapi==1.0
websocket-client==0.56.0
Werkzeug==0.15.2
wrapt==1.11.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xmltodict==0.12.0
yq==2.7.2
```

**Comment by juliohm1978** [comment]
python -v

```
> python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
import _locale # builtin
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
```

**Comment by tomplus** [comment]
It looks like your list of libraries is from python2, for example Cheetah==2.4.4 is for py2 only. Can you try to create virtualenv with python3 and required libraries and try to test it again. You can share output from `pip freeze` from the virtualenv. It helps me to try to reproduce problem on my pc.

**Comment by juliohm1978** [comment]
Ok, I managed to run the script inside [the official Docker image](https://hub.docker.com/_/python) using python:3.7.3-strech and it does work as expected. That's good news.

I'm closing this issue because it's clear now that my machine has conflicting python libraries installed. I'll have to manage to uninstall and reinstall all of python libs somehow.

Thank you for the help, @tomplus !
