### ISSUE TITLE
Invalid value for `items` - v1.list_namespaced_config_map

### ISSUE THREAD

**Issue by neliel123** [kubernetes-client/python#835]
I am using the following tools:
Python-Client : 8.0
Kubernetes Server: 1.10

```
async def config_maps():
    v1 = client.CoreV1Api()

    w = watch.Watch()
    for event in w.stream(v1.list_namespaced_config_map(namespace="test-namespace",watch=True, timeout_seconds=10)):
        logger.info("Event: %s %s %s" % (event['type'], event['object'].kind, event['object'].metadata.name))
        await asyncio.sleep(0)

def main():
    logger.info("logging:: Starting the watch....")
    
    ioloop = asyncio.get_event_loop()

    ioloop.create_task(config_maps())
    ioloop.run_forever()
```

I don't know why it is not returning any changes in my config map on my namespace.
So I added a timeout_seconds=10 and I see that an error is being raised when timeout is exceeded.

> ERROR:asyncio:Task exception was never retrieved
> future: <Task finished coro=<pods() done, defined at /usr/lib/python3.6/site-packages/kube/local_events.py:15> exception=ValueError('Invalid value for `items`, must not be `None`',)>
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/kube/local_events.py", line 22, in pods
>     for event in w.stream(v1.list_namespaced_config_map(namespace="test-namespace",watch=is_watch, timeout_seconds=10)):
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
>     (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
>     collection_formats=collection_formats)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
>     _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
>     return_data = self.deserialize(response_data, response_type)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
>     return self.__deserialize(data, response_type)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
>     return self.__deserialize_model(data, klass)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
>     instance = klass(**kwargs)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/models/v1_config_map_list.py", line 60, in __init__
>     self.items = items
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/models/v1_config_map_list.py", line 110, in items
>     raise ValueError("Invalid value for `items`, must not be `None`")
> ValueError: Invalid value for `items`, must not be `None`
> ^CTraceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/kube/local_events.py", line 51, in <module>
>     main()
>   File "/usr/lib/python3.6/site-packages/kube/local_events.py", line 48, in main
>     ioloop.run_forever()
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
>     self._run_once()
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
>     event_list = self._selector.select(timeout)
>   File "/usr/lib/python3.6/selectors.py", line 445, in select
>     fd_event_list = self._epoll.poll(timeout, max_ev)

Is this a known problem?

**Comment by neliel123** [comment]
Sorry made a mistake in my code. Please close as needed
